/* cu_compat.h -- OPTIONAL convenience aliases mapping the familiar
 * GMP/MPFR/MPC names to this library's cu_-prefixed symbols.
 *
 * Include this ONLY in translation units that do NOT also pull in the
 * system <gmp.h>/<mpfr.h>/<mpc.h>.  Code that links the system libraries
 * in the SAME binary should NOT include this header in its GPU sources and
 * should call the cu_-prefixed names (cu_mpfr_*, cu_mpc_*, cu_mpz_* ...)
 * directly so the two name sets never collide.
 *
 * Auto-generated from tools/cu_rename_syms.txt -- do not edit by hand. */
#ifndef MPC_CUDA_CU_COMPAT_H
#define MPC_CUDA_CU_COMPAT_H
#define __gmpfr_cache_const_catalan cu___gmpfr_cache_const_catalan
#define __gmpfr_cache_const_euler cu___gmpfr_cache_const_euler
#define __gmpfr_cache_const_log2 cu___gmpfr_cache_const_log2
#define __gmpfr_cache_const_pi cu___gmpfr_cache_const_pi
#define __gmpfr_ceil_exp2 cu___gmpfr_ceil_exp2
#define __gmpfr_ceil_log2 cu___gmpfr_ceil_log2
#define __gmpfr_const_log2_RNDD cu___gmpfr_const_log2_RNDD
#define __gmpfr_const_log2_RNDU cu___gmpfr_const_log2_RNDU
#define __gmpfr_cuberoot cu___gmpfr_cuberoot
#define __gmpfr_default_fp_bit_precision cu___gmpfr_default_fp_bit_precision
#define __gmpfr_default_rounding_mode cu___gmpfr_default_rounding_mode
#define __gmpfr_emax cu___gmpfr_emax
#define __gmpfr_emin cu___gmpfr_emin
#define __gmpfr_flags cu___gmpfr_flags
#define __gmpfr_floor_log2 cu___gmpfr_floor_log2
#define __gmpfr_four cu___gmpfr_four
#define __gmpfr_fpif_export cu___gmpfr_fpif_export
#define __gmpfr_fpif_import cu___gmpfr_fpif_import
#define __gmpfr_inp_str cu___gmpfr_inp_str
#define __gmpfr_int_ceil_log2 cu___gmpfr_int_ceil_log2
#define __gmpfr_isqrt cu___gmpfr_isqrt
#define __gmpfr_l2b cu___gmpfr_l2b
#define __gmpfr_mone cu___gmpfr_mone
#define __gmpfr_mpfr_get_sj cu___gmpfr_mpfr_get_sj
#define __gmpfr_mpfr_get_uj cu___gmpfr_mpfr_get_uj
#define __gmpfr_mpfr_pow_sj cu___gmpfr_mpfr_pow_sj
#define __gmpfr_mpfr_pow_uj cu___gmpfr_mpfr_pow_uj
#define __gmpfr_one cu___gmpfr_one
#define __gmpfr_out_str cu___gmpfr_out_str
#define __gmpfr_set_sj cu___gmpfr_set_sj
#define __gmpfr_set_sj_2exp cu___gmpfr_set_sj_2exp
#define __gmpfr_set_uj cu___gmpfr_set_uj
#define __gmpfr_set_uj_2exp cu___gmpfr_set_uj_2exp
#define __gmpfr_two cu___gmpfr_two
#define mp_bits_per_limb cu_mp_bits_per_limb
#define mpc_abs cu_mpc_abs
#define mpc_acos cu_mpc_acos
#define mpc_acosh cu_mpc_acosh
#define mpc_add cu_mpc_add
#define mpc_add_fr cu_mpc_add_fr
#define mpc_add_si cu_mpc_add_si
#define mpc_add_ui cu_mpc_add_ui
#define mpc_agm cu_mpc_agm
#define mpc_alloc_str cu_mpc_alloc_str
#define mpc_arg cu_mpc_arg
#define mpc_asin cu_mpc_asin
#define mpc_asinh cu_mpc_asinh
#define mpc_atan cu_mpc_atan
#define mpc_atanh cu_mpc_atanh
#define mpc_ceil_log2 cu_mpc_ceil_log2
#define mpc_clear cu_mpc_clear
#define mpc_cmp cu_mpc_cmp
#define mpc_cmp_abs cu_mpc_cmp_abs
#define mpc_cmp_si_si cu_mpc_cmp_si_si
#define mpc_conj cu_mpc_conj
#define mpc_cos cu_mpc_cos
#define mpc_cosh cu_mpc_cosh
#define mpc_div cu_mpc_div
#define mpc_div_2si cu_mpc_div_2si
#define mpc_div_2ui cu_mpc_div_2ui
#define mpc_div_fr cu_mpc_div_fr
#define mpc_div_ui cu_mpc_div_ui
#define mpc_dot cu_mpc_dot
#define mpc_eta_fund cu_mpc_eta_fund
#define mpc_exp cu_mpc_exp
#define mpc_exp10 cu_mpc_exp10
#define mpc_exp2 cu_mpc_exp2
#define mpc_fix_inf cu_mpc_fix_inf
#define mpc_fix_zero cu_mpc_fix_zero
#define mpc_fma cu_mpc_fma
#define mpc_fma_naive cu_mpc_fma_naive
#define mpc_fr_div cu_mpc_fr_div
#define mpc_fr_sub cu_mpc_fr_sub
#define mpc_free_str cu_mpc_free_str
#define mpc_get_prec cu_mpc_get_prec
#define mpc_get_prec2 cu_mpc_get_prec2
#define mpc_get_str cu_mpc_get_str
#define mpc_get_version cu_mpc_get_version
#define mpc_imag cu_mpc_imag
#define mpc_init2 cu_mpc_init2
#define mpc_init3 cu_mpc_init3
#define mpc_log cu_mpc_log
#define mpc_log2 cu_mpc_log2
#define mpc_mul cu_mpc_mul
#define mpc_mul_2si cu_mpc_mul_2si
#define mpc_mul_2ui cu_mpc_mul_2ui
#define mpc_mul_fr cu_mpc_mul_fr
#define mpc_mul_i cu_mpc_mul_i
#define mpc_mul_karatsuba cu_mpc_mul_karatsuba
#define mpc_mul_naive cu_mpc_mul_naive
#define mpc_mul_si cu_mpc_mul_si
#define mpc_mul_ui cu_mpc_mul_ui
#define mpc_neg cu_mpc_neg
#define mpc_norm cu_mpc_norm
#define mpc_pow_d cu_mpc_pow_d
#define mpc_pow_fr cu_mpc_pow_fr
#define mpc_pow_ld cu_mpc_pow_ld
#define mpc_pow_si cu_mpc_pow_si
#define mpc_pow_ui cu_mpc_pow_ui
#define mpc_pow_usi cu_mpc_pow_usi
#define mpc_pow_z cu_mpc_pow_z
#define mpc_proj cu_mpc_proj
#define mpc_real cu_mpc_real
#define mpc_realloc_str cu_mpc_realloc_str
#define mpc_set cu_mpc_set
#define mpc_set_d cu_mpc_set_d
#define mpc_set_d_d cu_mpc_set_d_d
#define mpc_set_f cu_mpc_set_f
#define mpc_set_f_f cu_mpc_set_f_f
#define mpc_set_fr cu_mpc_set_fr
#define mpc_set_fr_fr cu_mpc_set_fr_fr
#define mpc_set_ld cu_mpc_set_ld
#define mpc_set_ld_ld cu_mpc_set_ld_ld
#define mpc_set_nan cu_mpc_set_nan
#define mpc_set_prec cu_mpc_set_prec
#define mpc_set_q cu_mpc_set_q
#define mpc_set_q_q cu_mpc_set_q_q
#define mpc_set_si cu_mpc_set_si
#define mpc_set_si_si cu_mpc_set_si_si
#define mpc_set_sj cu_mpc_set_sj
#define mpc_set_sj_sj cu_mpc_set_sj_sj
#define mpc_set_str cu_mpc_set_str
#define mpc_set_ui cu_mpc_set_ui
#define mpc_set_ui_ui cu_mpc_set_ui_ui
#define mpc_set_uj cu_mpc_set_uj
#define mpc_set_uj_uj cu_mpc_set_uj_uj
#define mpc_set_z cu_mpc_set_z
#define mpc_set_z_z cu_mpc_set_z_z
#define mpc_sin cu_mpc_sin
#define mpc_sin_cos cu_mpc_sin_cos
#define mpc_sinh cu_mpc_sinh
#define mpc_sqr cu_mpc_sqr
#define mpc_sqrt cu_mpc_sqrt
#define mpc_strtoc cu_mpc_strtoc
#define mpc_sub cu_mpc_sub
#define mpc_sub_fr cu_mpc_sub_fr
#define mpc_sub_ui cu_mpc_sub_ui
#define mpc_sum cu_mpc_sum
#define mpc_swap cu_mpc_swap
#define mpc_tan cu_mpc_tan
#define mpc_tanh cu_mpc_tanh
#define mpc_ui_div cu_mpc_ui_div
#define mpc_ui_ui_sub cu_mpc_ui_ui_sub
#define mpc_urandom cu_mpc_urandom
#define mpfr_abort_prec_max cu_mpfr_abort_prec_max
#define mpfr_abs cu_mpfr_abs
#define mpfr_acos cu_mpfr_acos
#define mpfr_acosh cu_mpfr_acosh
#define mpfr_acospi cu_mpfr_acospi
#define mpfr_acosu cu_mpfr_acosu
#define mpfr_add cu_mpfr_add
#define mpfr_add1 cu_mpfr_add1
#define mpfr_add1sp cu_mpfr_add1sp
#define mpfr_add_d cu_mpfr_add_d
#define mpfr_add_si cu_mpfr_add_si
#define mpfr_add_ui cu_mpfr_add_ui
#define mpfr_add_z cu_mpfr_add_z
#define mpfr_agm cu_mpfr_agm
#define mpfr_ai cu_mpfr_ai
#define mpfr_allocate_func cu_mpfr_allocate_func
#define mpfr_asin cu_mpfr_asin
#define mpfr_asinh cu_mpfr_asinh
#define mpfr_asinpi cu_mpfr_asinpi
#define mpfr_asinu cu_mpfr_asinu
#define mpfr_assert_fail cu_mpfr_assert_fail
#define mpfr_atan cu_mpfr_atan
#define mpfr_atan2 cu_mpfr_atan2
#define mpfr_atan2pi cu_mpfr_atan2pi
#define mpfr_atan2u cu_mpfr_atan2u
#define mpfr_atanh cu_mpfr_atanh
#define mpfr_atanpi cu_mpfr_atanpi
#define mpfr_atanu cu_mpfr_atanu
#define mpfr_bases cu_mpfr_bases
#define mpfr_bernoulli_cache cu_mpfr_bernoulli_cache
#define mpfr_bernoulli_freecache cu_mpfr_bernoulli_freecache
#define mpfr_beta cu_mpfr_beta
#define mpfr_buildopt_decimal_p cu_mpfr_buildopt_decimal_p
#define mpfr_buildopt_float128_p cu_mpfr_buildopt_float128_p
#define mpfr_buildopt_gmpinternals_p cu_mpfr_buildopt_gmpinternals_p
#define mpfr_buildopt_sharedcache_p cu_mpfr_buildopt_sharedcache_p
#define mpfr_buildopt_tls_p cu_mpfr_buildopt_tls_p
#define mpfr_buildopt_tune_case cu_mpfr_buildopt_tune_case
#define mpfr_cache cu_mpfr_cache
#define mpfr_can_round cu_mpfr_can_round
#define mpfr_can_round_raw cu_mpfr_can_round_raw
#define mpfr_cbrt cu_mpfr_cbrt
#define mpfr_ceil cu_mpfr_ceil
#define mpfr_ceil_mul cu_mpfr_ceil_mul
#define mpfr_check cu_mpfr_check
#define mpfr_check_range cu_mpfr_check_range
#define mpfr_clear cu_mpfr_clear
#define mpfr_clear_cache cu_mpfr_clear_cache
#define mpfr_clear_divby0 cu_mpfr_clear_divby0
#define mpfr_clear_erangeflag cu_mpfr_clear_erangeflag
#define mpfr_clear_flags cu_mpfr_clear_flags
#define mpfr_clear_inexflag cu_mpfr_clear_inexflag
#define mpfr_clear_nanflag cu_mpfr_clear_nanflag
#define mpfr_clear_overflow cu_mpfr_clear_overflow
#define mpfr_clear_underflow cu_mpfr_clear_underflow
#define mpfr_clears cu_mpfr_clears
#define mpfr_clz_tab cu_mpfr_clz_tab
#define mpfr_cmp cu_mpfr_cmp
#define mpfr_cmp2 cu_mpfr_cmp2
#define mpfr_cmp3 cu_mpfr_cmp3
#define mpfr_cmp_d cu_mpfr_cmp_d
#define mpfr_cmp_ld cu_mpfr_cmp_ld
#define mpfr_cmp_si cu_mpfr_cmp_si
#define mpfr_cmp_si_2exp cu_mpfr_cmp_si_2exp
#define mpfr_cmp_ui cu_mpfr_cmp_ui
#define mpfr_cmp_ui_2exp cu_mpfr_cmp_ui_2exp
#define mpfr_cmp_z cu_mpfr_cmp_z
#define mpfr_cmpabs cu_mpfr_cmpabs
#define mpfr_cmpabs_ui cu_mpfr_cmpabs_ui
#define mpfr_compound_si cu_mpfr_compound_si
#define mpfr_const_catalan cu_mpfr_const_catalan
#define mpfr_const_catalan_internal cu_mpfr_const_catalan_internal
#define mpfr_const_euler cu_mpfr_const_euler
#define mpfr_const_euler_internal cu_mpfr_const_euler_internal
#define mpfr_const_log2 cu_mpfr_const_log2
#define mpfr_const_log2_internal cu_mpfr_const_log2_internal
#define mpfr_const_pi cu_mpfr_const_pi
#define mpfr_const_pi_internal cu_mpfr_const_pi_internal
#define mpfr_copysign cu_mpfr_copysign
#define mpfr_cos cu_mpfr_cos
#define mpfr_cosh cu_mpfr_cosh
#define mpfr_cospi cu_mpfr_cospi
#define mpfr_cosu cu_mpfr_cosu
#define mpfr_cot cu_mpfr_cot
#define mpfr_coth cu_mpfr_coth
#define mpfr_csc cu_mpfr_csc
#define mpfr_csch cu_mpfr_csch
#define mpfr_custom_get_exp cu_mpfr_custom_get_exp
#define mpfr_custom_get_kind cu_mpfr_custom_get_kind
#define mpfr_custom_get_significand cu_mpfr_custom_get_significand
#define mpfr_custom_get_size cu_mpfr_custom_get_size
#define mpfr_custom_init cu_mpfr_custom_init
#define mpfr_custom_init_set cu_mpfr_custom_init_set
#define mpfr_custom_move cu_mpfr_custom_move
#define mpfr_d_div cu_mpfr_d_div
#define mpfr_d_sub cu_mpfr_d_sub
#define mpfr_digamma cu_mpfr_digamma
#define mpfr_dim cu_mpfr_dim
#define mpfr_div cu_mpfr_div
#define mpfr_div_2exp cu_mpfr_div_2exp
#define mpfr_div_2si cu_mpfr_div_2si
#define mpfr_div_2ui cu_mpfr_div_2ui
#define mpfr_div_d cu_mpfr_div_d
#define mpfr_div_si cu_mpfr_div_si
#define mpfr_div_ui cu_mpfr_div_ui
#define mpfr_div_ui2 cu_mpfr_div_ui2
#define mpfr_div_z cu_mpfr_div_z
#define mpfr_divby0_p cu_mpfr_divby0_p
#define mpfr_divhigh_n cu_mpfr_divhigh_n
#define mpfr_dot cu_mpfr_dot
#define mpfr_eint cu_mpfr_eint
#define mpfr_eq cu_mpfr_eq
#define mpfr_equal_p cu_mpfr_equal_p
#define mpfr_erandom cu_mpfr_erandom
#define mpfr_erangeflag_p cu_mpfr_erangeflag_p
#define mpfr_erf cu_mpfr_erf
#define mpfr_erfc cu_mpfr_erfc
#define mpfr_exp cu_mpfr_exp
#define mpfr_exp10 cu_mpfr_exp10
#define mpfr_exp10m1 cu_mpfr_exp10m1
#define mpfr_exp2 cu_mpfr_exp2
#define mpfr_exp2m1 cu_mpfr_exp2m1
#define mpfr_exp_2 cu_mpfr_exp_2
#define mpfr_exp_3 cu_mpfr_exp_3
#define mpfr_expm1 cu_mpfr_expm1
#define mpfr_extract cu_mpfr_extract
#define mpfr_fac_ui cu_mpfr_fac_ui
#define mpfr_fits_intmax_p cu_mpfr_fits_intmax_p
#define mpfr_fits_sint_p cu_mpfr_fits_sint_p
#define mpfr_fits_slong_p cu_mpfr_fits_slong_p
#define mpfr_fits_sshort_p cu_mpfr_fits_sshort_p
#define mpfr_fits_uint_p cu_mpfr_fits_uint_p
#define mpfr_fits_uintmax_p cu_mpfr_fits_uintmax_p
#define mpfr_fits_ulong_p cu_mpfr_fits_ulong_p
#define mpfr_fits_ushort_p cu_mpfr_fits_ushort_p
#define mpfr_flags_clear cu_mpfr_flags_clear
#define mpfr_flags_restore cu_mpfr_flags_restore
#define mpfr_flags_save cu_mpfr_flags_save
#define mpfr_flags_set cu_mpfr_flags_set
#define mpfr_flags_test cu_mpfr_flags_test
#define mpfr_floor cu_mpfr_floor
#define mpfr_fma cu_mpfr_fma
#define mpfr_fmma cu_mpfr_fmma
#define mpfr_fmms cu_mpfr_fmms
#define mpfr_fmod cu_mpfr_fmod
#define mpfr_fmod_ui cu_mpfr_fmod_ui
#define mpfr_fmodquo cu_mpfr_fmodquo
#define mpfr_fms cu_mpfr_fms
#define mpfr_frac cu_mpfr_frac
#define mpfr_free_cache cu_mpfr_free_cache
#define mpfr_free_cache2 cu_mpfr_free_cache2
#define mpfr_free_func cu_mpfr_free_func
#define mpfr_free_pool cu_mpfr_free_pool
#define mpfr_free_str cu_mpfr_free_str
#define mpfr_frexp cu_mpfr_frexp
#define mpfr_gamma cu_mpfr_gamma
#define mpfr_gamma_inc cu_mpfr_gamma_inc
#define mpfr_gamma_one_and_two_third cu_mpfr_gamma_one_and_two_third
#define mpfr_get_d cu_mpfr_get_d
#define mpfr_get_d1 cu_mpfr_get_d1
#define mpfr_get_d_2exp cu_mpfr_get_d_2exp
#define mpfr_get_default_prec cu_mpfr_get_default_prec
#define mpfr_get_default_rounding_mode cu_mpfr_get_default_rounding_mode
#define mpfr_get_emax cu_mpfr_get_emax
#define mpfr_get_emax_max cu_mpfr_get_emax_max
#define mpfr_get_emax_min cu_mpfr_get_emax_min
#define mpfr_get_emin cu_mpfr_get_emin
#define mpfr_get_emin_max cu_mpfr_get_emin_max
#define mpfr_get_emin_min cu_mpfr_get_emin_min
#define mpfr_get_exp cu_mpfr_get_exp
#define mpfr_get_flt cu_mpfr_get_flt
#define mpfr_get_ld cu_mpfr_get_ld
#define mpfr_get_ld_2exp cu_mpfr_get_ld_2exp
#define mpfr_get_patches cu_mpfr_get_patches
#define mpfr_get_prec cu_mpfr_get_prec
#define mpfr_get_si cu_mpfr_get_si
#define mpfr_get_str cu_mpfr_get_str
#define mpfr_get_str_ndigits cu_mpfr_get_str_ndigits
#define mpfr_get_ui cu_mpfr_get_ui
#define mpfr_get_version cu_mpfr_get_version
#define mpfr_get_z cu_mpfr_get_z
#define mpfr_get_z_2exp cu_mpfr_get_z_2exp
#define mpfr_grandom cu_mpfr_grandom
#define mpfr_greater_p cu_mpfr_greater_p
#define mpfr_greaterequal_p cu_mpfr_greaterequal_p
#define mpfr_hypot cu_mpfr_hypot
#define mpfr_inexflag_p cu_mpfr_inexflag_p
#define mpfr_inf_p cu_mpfr_inf_p
#define mpfr_init cu_mpfr_init
#define mpfr_init2 cu_mpfr_init2
#define mpfr_init_set_str cu_mpfr_init_set_str
#define mpfr_inits cu_mpfr_inits
#define mpfr_inits2 cu_mpfr_inits2
#define mpfr_integer_p cu_mpfr_integer_p
#define mpfr_j0 cu_mpfr_j0
#define mpfr_j1 cu_mpfr_j1
#define mpfr_jn cu_mpfr_jn
#define mpfr_less_p cu_mpfr_less_p
#define mpfr_lessequal_p cu_mpfr_lessequal_p
#define mpfr_lessgreater_p cu_mpfr_lessgreater_p
#define mpfr_lgamma cu_mpfr_lgamma
#define mpfr_li2 cu_mpfr_li2
#define mpfr_lngamma cu_mpfr_lngamma
#define mpfr_log cu_mpfr_log
#define mpfr_log10 cu_mpfr_log10
#define mpfr_log10p1 cu_mpfr_log10p1
#define mpfr_log1p cu_mpfr_log1p
#define mpfr_log2 cu_mpfr_log2
#define mpfr_log2p1 cu_mpfr_log2p1
#define mpfr_log_ui cu_mpfr_log_ui
#define mpfr_max cu_mpfr_max
#define mpfr_min cu_mpfr_min
#define mpfr_min_prec cu_mpfr_min_prec
#define mpfr_modf cu_mpfr_modf
#define mpfr_mp_memory_cleanup cu_mpfr_mp_memory_cleanup
#define mpfr_mpn_exp cu_mpfr_mpn_exp
#define mpfr_mul cu_mpfr_mul
#define mpfr_mul_2exp cu_mpfr_mul_2exp
#define mpfr_mul_2si cu_mpfr_mul_2si
#define mpfr_mul_2ui cu_mpfr_mul_2ui
#define mpfr_mul_d cu_mpfr_mul_d
#define mpfr_mul_si cu_mpfr_mul_si
#define mpfr_mul_ui cu_mpfr_mul_ui
#define mpfr_mul_z cu_mpfr_mul_z
#define mpfr_mulhigh_n cu_mpfr_mulhigh_n
#define mpfr_nan_p cu_mpfr_nan_p
#define mpfr_nanflag_p cu_mpfr_nanflag_p
#define mpfr_nbits_uj cu_mpfr_nbits_uj
#define mpfr_nbits_ulong cu_mpfr_nbits_ulong
#define mpfr_neg cu_mpfr_neg
#define mpfr_nextabove cu_mpfr_nextabove
#define mpfr_nextbelow cu_mpfr_nextbelow
#define mpfr_nexttoinf cu_mpfr_nexttoinf
#define mpfr_nexttoward cu_mpfr_nexttoward
#define mpfr_nexttozero cu_mpfr_nexttozero
#define mpfr_nrandom cu_mpfr_nrandom
#define mpfr_number_p cu_mpfr_number_p
#define mpfr_odd_p cu_mpfr_odd_p
#define mpfr_overflow cu_mpfr_overflow
#define mpfr_overflow_p cu_mpfr_overflow_p
#define mpfr_pow cu_mpfr_pow
#define mpfr_pow_general cu_mpfr_pow_general
#define mpfr_pow_si cu_mpfr_pow_si
#define mpfr_pow_ui cu_mpfr_pow_ui
#define mpfr_pow_z cu_mpfr_pow_z
#define mpfr_powerof2_raw cu_mpfr_powerof2_raw
#define mpfr_powerof2_raw2 cu_mpfr_powerof2_raw2
#define mpfr_powr cu_mpfr_powr
#define mpfr_prec_round cu_mpfr_prec_round
#define mpfr_print_mant_binary cu_mpfr_print_mant_binary
#define mpfr_print_rnd_mode cu_mpfr_print_rnd_mode
#define mpfr_rand_raw cu_mpfr_rand_raw
#define mpfr_random_deviate_clear cu_mpfr_random_deviate_clear
#define mpfr_random_deviate_init cu_mpfr_random_deviate_init
#define mpfr_random_deviate_less cu_mpfr_random_deviate_less
#define mpfr_random_deviate_reset cu_mpfr_random_deviate_reset
#define mpfr_random_deviate_swap cu_mpfr_random_deviate_swap
#define mpfr_random_deviate_tstbit cu_mpfr_random_deviate_tstbit
#define mpfr_random_deviate_value cu_mpfr_random_deviate_value
#define mpfr_reallocate_func cu_mpfr_reallocate_func
#define mpfr_rec_sqrt cu_mpfr_rec_sqrt
#define mpfr_regular_p cu_mpfr_regular_p
#define mpfr_reldiff cu_mpfr_reldiff
#define mpfr_remainder cu_mpfr_remainder
#define mpfr_remquo cu_mpfr_remquo
#define mpfr_rint cu_mpfr_rint
#define mpfr_rint_ceil cu_mpfr_rint_ceil
#define mpfr_rint_floor cu_mpfr_rint_floor
#define mpfr_rint_round cu_mpfr_rint_round
#define mpfr_rint_roundeven cu_mpfr_rint_roundeven
#define mpfr_rint_trunc cu_mpfr_rint_trunc
#define mpfr_root cu_mpfr_root
#define mpfr_rootn_si cu_mpfr_rootn_si
#define mpfr_rootn_ui cu_mpfr_rootn_ui
#define mpfr_round cu_mpfr_round
#define mpfr_round_near_x cu_mpfr_round_near_x
#define mpfr_round_nearest_away_begin cu_mpfr_round_nearest_away_begin
#define mpfr_round_nearest_away_end cu_mpfr_round_nearest_away_end
#define mpfr_round_p cu_mpfr_round_p
#define mpfr_round_raw cu_mpfr_round_raw
#define mpfr_round_raw_2 cu_mpfr_round_raw_2
#define mpfr_round_raw_4 cu_mpfr_round_raw_4
#define mpfr_roundeven cu_mpfr_roundeven
#define mpfr_scale2 cu_mpfr_scale2
#define mpfr_sec cu_mpfr_sec
#define mpfr_sech cu_mpfr_sech
#define mpfr_set cu_mpfr_set
#define mpfr_set4 cu_mpfr_set4
#define mpfr_set_1_2 cu_mpfr_set_1_2
#define mpfr_set_d cu_mpfr_set_d
#define mpfr_set_default_prec cu_mpfr_set_default_prec
#define mpfr_set_default_rounding_mode cu_mpfr_set_default_rounding_mode
#define mpfr_set_divby0 cu_mpfr_set_divby0
#define mpfr_set_emax cu_mpfr_set_emax
#define mpfr_set_emin cu_mpfr_set_emin
#define mpfr_set_erangeflag cu_mpfr_set_erangeflag
#define mpfr_set_exp cu_mpfr_set_exp
#define mpfr_set_flt cu_mpfr_set_flt
#define mpfr_set_inexflag cu_mpfr_set_inexflag
#define mpfr_set_inf cu_mpfr_set_inf
#define mpfr_set_ld cu_mpfr_set_ld
#define mpfr_set_nan cu_mpfr_set_nan
#define mpfr_set_nanflag cu_mpfr_set_nanflag
#define mpfr_set_overflow cu_mpfr_set_overflow
#define mpfr_set_prec cu_mpfr_set_prec
#define mpfr_set_prec_raw cu_mpfr_set_prec_raw
#define mpfr_set_si cu_mpfr_set_si
#define mpfr_set_si_2exp cu_mpfr_set_si_2exp
#define mpfr_set_str cu_mpfr_set_str
#define mpfr_set_str_binary cu_mpfr_set_str_binary
#define mpfr_set_ui cu_mpfr_set_ui
#define mpfr_set_ui_2exp cu_mpfr_set_ui_2exp
#define mpfr_set_underflow cu_mpfr_set_underflow
#define mpfr_set_z cu_mpfr_set_z
#define mpfr_set_z_2exp cu_mpfr_set_z_2exp
#define mpfr_set_zero cu_mpfr_set_zero
#define mpfr_setmax cu_mpfr_setmax
#define mpfr_setmin cu_mpfr_setmin
#define mpfr_setsign cu_mpfr_setsign
#define mpfr_sgn cu_mpfr_sgn
#define mpfr_si_div cu_mpfr_si_div
#define mpfr_si_sub cu_mpfr_si_sub
#define mpfr_signbit cu_mpfr_signbit
#define mpfr_sin cu_mpfr_sin
#define mpfr_sin_cos cu_mpfr_sin_cos
#define mpfr_sincos_fast cu_mpfr_sincos_fast
#define mpfr_sinh cu_mpfr_sinh
#define mpfr_sinh_cosh cu_mpfr_sinh_cosh
#define mpfr_sinpi cu_mpfr_sinpi
#define mpfr_sinu cu_mpfr_sinu
#define mpfr_sqr cu_mpfr_sqr
#define mpfr_sqrhigh_n cu_mpfr_sqrhigh_n
#define mpfr_sqrt cu_mpfr_sqrt
#define mpfr_sqrt_ui cu_mpfr_sqrt_ui
#define mpfr_strtofr cu_mpfr_strtofr
#define mpfr_sub cu_mpfr_sub
#define mpfr_sub1 cu_mpfr_sub1
#define mpfr_sub1sp cu_mpfr_sub1sp
#define mpfr_sub_d cu_mpfr_sub_d
#define mpfr_sub_si cu_mpfr_sub_si
#define mpfr_sub_ui cu_mpfr_sub_ui
#define mpfr_sub_z cu_mpfr_sub_z
#define mpfr_subnormalize cu_mpfr_subnormalize
#define mpfr_sum cu_mpfr_sum
#define mpfr_swap cu_mpfr_swap
#define mpfr_tan cu_mpfr_tan
#define mpfr_tanh cu_mpfr_tanh
#define mpfr_tanpi cu_mpfr_tanpi
#define mpfr_tanu cu_mpfr_tanu
#define mpfr_tmp_allocate cu_mpfr_tmp_allocate
#define mpfr_tmp_free cu_mpfr_tmp_free
#define mpfr_total_order_p cu_mpfr_total_order_p
#define mpfr_trunc cu_mpfr_trunc
#define mpfr_ubf_diff_exp cu_mpfr_ubf_diff_exp
#define mpfr_ubf_exp_less_p cu_mpfr_ubf_exp_less_p
#define mpfr_ubf_mul_exact cu_mpfr_ubf_mul_exact
#define mpfr_ubf_zexp2exp cu_mpfr_ubf_zexp2exp
#define mpfr_ui_div cu_mpfr_ui_div
#define mpfr_ui_pow cu_mpfr_ui_pow
#define mpfr_ui_pow_ui cu_mpfr_ui_pow_ui
#define mpfr_ui_sub cu_mpfr_ui_sub
#define mpfr_underflow cu_mpfr_underflow
#define mpfr_underflow_p cu_mpfr_underflow_p
#define mpfr_unordered_p cu_mpfr_unordered_p
#define mpfr_urandom cu_mpfr_urandom
#define mpfr_urandomb cu_mpfr_urandomb
#define mpfr_y0 cu_mpfr_y0
#define mpfr_y1 cu_mpfr_y1
#define mpfr_yn cu_mpfr_yn
#define mpfr_z_sub cu_mpfr_z_sub
#define mpfr_zero_p cu_mpfr_zero_p
#define mpfr_zeta cu_mpfr_zeta
#define mpfr_zeta_ui cu_mpfr_zeta_ui
#define mpn_add cu_mpn_add
#define mpn_add_1 cu_mpn_add_1
#define mpn_add_n cu_mpn_add_n
#define mpn_addmul_1 cu_mpn_addmul_1
#define mpn_cmp cu_mpn_cmp
#define mpn_com cu_mpn_com
#define mpn_copyd cu_mpn_copyd
#define mpn_copyi cu_mpn_copyi
#define mpn_get_str cu_mpn_get_str
#define mpn_invert_3by2 cu_mpn_invert_3by2
#define mpn_lshift cu_mpn_lshift
#define mpn_mul cu_mpn_mul
#define mpn_mul_1 cu_mpn_mul_1
#define mpn_mul_n cu_mpn_mul_n
#define mpn_neg cu_mpn_neg
#define mpn_perfect_square_p cu_mpn_perfect_square_p
#define mpn_popcount cu_mpn_popcount
#define mpn_rshift cu_mpn_rshift
#define mpn_scan0 cu_mpn_scan0
#define mpn_scan1 cu_mpn_scan1
#define mpn_set_str cu_mpn_set_str
#define mpn_sqr cu_mpn_sqr
#define mpn_sqrtrem cu_mpn_sqrtrem
#define mpn_sub cu_mpn_sub
#define mpn_sub_1 cu_mpn_sub_1
#define mpn_sub_n cu_mpn_sub_n
#define mpn_submul_1 cu_mpn_submul_1
#define mpn_zero cu_mpn_zero
#define mpn_zero_p cu_mpn_zero_p
#define mpz_2fac_ui cu_mpz_2fac_ui
#define mpz_abs cu_mpz_abs
#define mpz_add cu_mpz_add
#define mpz_add_ui cu_mpz_add_ui
#define mpz_addmul cu_mpz_addmul
#define mpz_addmul_ui cu_mpz_addmul_ui
#define mpz_and cu_mpz_and
#define mpz_bin_uiui cu_mpz_bin_uiui
#define mpz_cdiv_q cu_mpz_cdiv_q
#define mpz_cdiv_q_2exp cu_mpz_cdiv_q_2exp
#define mpz_cdiv_q_ui cu_mpz_cdiv_q_ui
#define mpz_cdiv_qr cu_mpz_cdiv_qr
#define mpz_cdiv_qr_ui cu_mpz_cdiv_qr_ui
#define mpz_cdiv_r cu_mpz_cdiv_r
#define mpz_cdiv_r_2exp cu_mpz_cdiv_r_2exp
#define mpz_cdiv_r_ui cu_mpz_cdiv_r_ui
#define mpz_cdiv_ui cu_mpz_cdiv_ui
#define mpz_clear cu_mpz_clear
#define mpz_clrbit cu_mpz_clrbit
#define mpz_cmp cu_mpz_cmp
#define mpz_cmp_d cu_mpz_cmp_d
#define mpz_cmp_si cu_mpz_cmp_si
#define mpz_cmp_ui cu_mpz_cmp_ui
#define mpz_cmpabs cu_mpz_cmpabs
#define mpz_cmpabs_d cu_mpz_cmpabs_d
#define mpz_cmpabs_ui cu_mpz_cmpabs_ui
#define mpz_com cu_mpz_com
#define mpz_combit cu_mpz_combit
#define mpz_congruent_p cu_mpz_congruent_p
#define mpz_divexact cu_mpz_divexact
#define mpz_divexact_ui cu_mpz_divexact_ui
#define mpz_divisible_p cu_mpz_divisible_p
#define mpz_divisible_ui_p cu_mpz_divisible_ui_p
#define mpz_export cu_mpz_export
#define mpz_fac_ui cu_mpz_fac_ui
#define mpz_fdiv_q cu_mpz_fdiv_q
#define mpz_fdiv_q_2exp cu_mpz_fdiv_q_2exp
#define mpz_fdiv_q_ui cu_mpz_fdiv_q_ui
#define mpz_fdiv_qr cu_mpz_fdiv_qr
#define mpz_fdiv_qr_ui cu_mpz_fdiv_qr_ui
#define mpz_fdiv_r cu_mpz_fdiv_r
#define mpz_fdiv_r_2exp cu_mpz_fdiv_r_2exp
#define mpz_fdiv_r_ui cu_mpz_fdiv_r_ui
#define mpz_fdiv_ui cu_mpz_fdiv_ui
#define mpz_fits_sint_p cu_mpz_fits_sint_p
#define mpz_fits_slong_p cu_mpz_fits_slong_p
#define mpz_fits_sshort_p cu_mpz_fits_sshort_p
#define mpz_fits_uint_p cu_mpz_fits_uint_p
#define mpz_fits_ulong_p cu_mpz_fits_ulong_p
#define mpz_fits_ushort_p cu_mpz_fits_ushort_p
#define mpz_gcd cu_mpz_gcd
#define mpz_gcd_ui cu_mpz_gcd_ui
#define mpz_gcdext cu_mpz_gcdext
#define mpz_get_d cu_mpz_get_d
#define mpz_get_si cu_mpz_get_si
#define mpz_get_str cu_mpz_get_str
#define mpz_get_ui cu_mpz_get_ui
#define mpz_getlimbn cu_mpz_getlimbn
#define mpz_hamdist cu_mpz_hamdist
#define mpz_import cu_mpz_import
#define mpz_init cu_mpz_init
#define mpz_init2 cu_mpz_init2
#define mpz_init_set cu_mpz_init_set
#define mpz_init_set_d cu_mpz_init_set_d
#define mpz_init_set_si cu_mpz_init_set_si
#define mpz_init_set_str cu_mpz_init_set_str
#define mpz_init_set_ui cu_mpz_init_set_ui
#define mpz_invert cu_mpz_invert
#define mpz_ior cu_mpz_ior
#define mpz_lcm cu_mpz_lcm
#define mpz_lcm_ui cu_mpz_lcm_ui
#define mpz_limbs_finish cu_mpz_limbs_finish
#define mpz_limbs_modify cu_mpz_limbs_modify
#define mpz_limbs_read cu_mpz_limbs_read
#define mpz_limbs_write cu_mpz_limbs_write
#define mpz_mfac_uiui cu_mpz_mfac_uiui
#define mpz_mod cu_mpz_mod
#define mpz_mod_ui cu_mpz_mod_ui
#define mpz_mul cu_mpz_mul
#define mpz_mul_2exp cu_mpz_mul_2exp
#define mpz_mul_si cu_mpz_mul_si
#define mpz_mul_ui cu_mpz_mul_ui
#define mpz_neg cu_mpz_neg
#define mpz_out_str cu_mpz_out_str
#define mpz_perfect_square_p cu_mpz_perfect_square_p
#define mpz_popcount cu_mpz_popcount
#define mpz_pow_ui cu_mpz_pow_ui
#define mpz_powm cu_mpz_powm
#define mpz_powm_ui cu_mpz_powm_ui
#define mpz_probab_prime_p cu_mpz_probab_prime_p
#define mpz_realloc2 cu_mpz_realloc2
#define mpz_roinit_n cu_mpz_roinit_n
#define mpz_root cu_mpz_root
#define mpz_rootrem cu_mpz_rootrem
#define mpz_scan0 cu_mpz_scan0
#define mpz_scan1 cu_mpz_scan1
#define mpz_set cu_mpz_set
#define mpz_set_d cu_mpz_set_d
#define mpz_set_si cu_mpz_set_si
#define mpz_set_str cu_mpz_set_str
#define mpz_set_ui cu_mpz_set_ui
#define mpz_setbit cu_mpz_setbit
#define mpz_sgn cu_mpz_sgn
#define mpz_size cu_mpz_size
#define mpz_sizeinbase cu_mpz_sizeinbase
#define mpz_sqrt cu_mpz_sqrt
#define mpz_sqrtrem cu_mpz_sqrtrem
#define mpz_sub cu_mpz_sub
#define mpz_sub_ui cu_mpz_sub_ui
#define mpz_submul cu_mpz_submul
#define mpz_submul_ui cu_mpz_submul_ui
#define mpz_swap cu_mpz_swap
#define mpz_tdiv_q cu_mpz_tdiv_q
#define mpz_tdiv_q_2exp cu_mpz_tdiv_q_2exp
#define mpz_tdiv_q_ui cu_mpz_tdiv_q_ui
#define mpz_tdiv_qr cu_mpz_tdiv_qr
#define mpz_tdiv_qr_ui cu_mpz_tdiv_qr_ui
#define mpz_tdiv_r cu_mpz_tdiv_r
#define mpz_tdiv_r_2exp cu_mpz_tdiv_r_2exp
#define mpz_tdiv_r_ui cu_mpz_tdiv_r_ui
#define mpz_tdiv_ui cu_mpz_tdiv_ui
#define mpz_tstbit cu_mpz_tstbit
#define mpz_ui_pow_ui cu_mpz_ui_pow_ui
#define mpz_ui_sub cu_mpz_ui_sub
#define mpz_xor cu_mpz_xor
#endif /* MPC_CUDA_CU_COMPAT_H */
