/* Auto-generated by tools/make_umbrella.py -- do NOT edit by hand.
 * Fully cu_/CU_-namespaced public header: every type, enum constant,
 * macro and include guard is prefixed so this coexists with the system
 * <gmp.h>/<mpfr.h>/<mpc.h> in the SAME translation unit. */
#ifndef CU_MPC_CUDA_GMP_H
#define CU_MPC_CUDA_GMP_H
#include <stddef.h>
/* Build-time constants the cudafied library was compiled with; the public
 * headers need them too so users do not have to pass any -D flags. */
#ifndef CU_GMP_NUMB_BITS
#define CU_GMP_NUMB_BITS 64
#endif
#ifndef CU_MPFR_USE_MINI_GMP
#define CU_MPFR_USE_MINI_GMP 1
#endif
/* Auto-generated from mini-gmp.h by tools/cudafy_minigmp.py.  Do not edit by hand. */
/* mini-gmp, a minimalistic implementation of a GNU GMP subset.

Copyright 2011-2015, 2017, 2019-2021 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

/* About mini-gmp: This is a minimal implementation of a subset of the
   GMP interface. It is intended for inclusion into applications which
   have modest bignums needs, as a fallback when the real GMP library
   is not installed.

   This file defines the public interface. */


/* For size_t */

#if defined (__cplusplus)
extern "C" {
#endif

void cu_mp_set_memory_functions (void *(*) (size_t),
			      void *(*) (void *, size_t, size_t),
			      void (*) (void *, size_t));

void cu_mp_get_memory_functions (void *(**) (size_t),
			      void *(**) (void *, size_t, size_t),
			      void (**) (void *, size_t));

#ifndef MINI_GMP_LIMB_TYPE
#define MINI_GMP_LIMB_TYPE long
#endif

typedef unsigned MINI_GMP_LIMB_TYPE cu_mp_limb_t;
typedef long cu_mp_size_t;
typedef unsigned long cu_mp_bitcnt_t;

typedef cu_mp_limb_t *mp_ptr;
typedef const cu_mp_limb_t *mp_srcptr;

typedef struct
{
  int _mp_alloc;		/* Number of *limbs* allocated and pointed
				   to by the _mp_d field.  */
  int _mp_size;			/* abs(_mp_size) is the number of limbs the
				   last field points to.  If _mp_size is
				   negative this is a negative number.  */
  cu_mp_limb_t *_mp_d;		/* Pointer to the limbs.  */
} cu___mpz_struct;

typedef cu___mpz_struct cu_mpz_t[1];

typedef cu___mpz_struct *cu_mpz_ptr;
typedef const cu___mpz_struct *cu_mpz_srcptr;

extern __device__ __managed__ int cu_mp_bits_per_limb;

__host__ __device__ void cu_mpn_copyi (mp_ptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ void cu_mpn_copyd (mp_ptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ void cu_mpn_zero (mp_ptr, cu_mp_size_t);

__host__ __device__ int cu_mpn_cmp (mp_srcptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ int cu_mpn_zero_p (mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_limb_t cu_mpn_add_1 (mp_ptr, mp_srcptr, cu_mp_size_t, cu_mp_limb_t);
__host__ __device__ cu_mp_limb_t cu_mpn_add_n (mp_ptr, mp_srcptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ cu_mp_limb_t cu_mpn_add (mp_ptr, mp_srcptr, cu_mp_size_t, mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_limb_t cu_mpn_sub_1 (mp_ptr, mp_srcptr, cu_mp_size_t, cu_mp_limb_t);
__host__ __device__ cu_mp_limb_t cu_mpn_sub_n (mp_ptr, mp_srcptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ cu_mp_limb_t cu_mpn_sub (mp_ptr, mp_srcptr, cu_mp_size_t, mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_limb_t cu_mpn_mul_1 (mp_ptr, mp_srcptr, cu_mp_size_t, cu_mp_limb_t);
__host__ __device__ cu_mp_limb_t cu_mpn_addmul_1 (mp_ptr, mp_srcptr, cu_mp_size_t, cu_mp_limb_t);
__host__ __device__ cu_mp_limb_t cu_mpn_submul_1 (mp_ptr, mp_srcptr, cu_mp_size_t, cu_mp_limb_t);

__host__ __device__ cu_mp_limb_t cu_mpn_mul (mp_ptr, mp_srcptr, cu_mp_size_t, mp_srcptr, cu_mp_size_t);
__host__ __device__ void cu_mpn_mul_n (mp_ptr, mp_srcptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ void cu_mpn_sqr (mp_ptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ int cu_mpn_perfect_square_p (mp_srcptr, cu_mp_size_t);
__host__ __device__ cu_mp_size_t cu_mpn_sqrtrem (mp_ptr, mp_ptr, mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_limb_t cu_mpn_lshift (mp_ptr, mp_srcptr, cu_mp_size_t, unsigned int);
__host__ __device__ cu_mp_limb_t cu_mpn_rshift (mp_ptr, mp_srcptr, cu_mp_size_t, unsigned int);

__host__ __device__ cu_mp_bitcnt_t cu_mpn_scan0 (mp_srcptr, cu_mp_bitcnt_t);
__host__ __device__ cu_mp_bitcnt_t cu_mpn_scan1 (mp_srcptr, cu_mp_bitcnt_t);

__host__ __device__ void cu_mpn_com (mp_ptr, mp_srcptr, cu_mp_size_t);
__host__ __device__ cu_mp_limb_t cu_mpn_neg (mp_ptr, mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_bitcnt_t cu_mpn_popcount (mp_srcptr, cu_mp_size_t);

__host__ __device__ cu_mp_limb_t cu_mpn_invert_3by2 (cu_mp_limb_t, cu_mp_limb_t);
#define cu_mpn_invert_limb(x) cu_mpn_invert_3by2 ((x), 0)

__host__ __device__ size_t cu_mpn_get_str (unsigned char *, int, mp_ptr, cu_mp_size_t);
__host__ __device__ cu_mp_size_t cu_mpn_set_str (mp_ptr, const unsigned char *, size_t, int);

__host__ __device__ void cu_mpz_init (cu_mpz_t);
__host__ __device__ void cu_mpz_init2 (cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_clear (cu_mpz_t);

#define cu_mpz_odd_p(z)   (((z)->_mp_size != 0) & (int) (z)->_mp_d[0])
#define cu_mpz_even_p(z)  (! cu_mpz_odd_p (z))

__host__ __device__ int cu_mpz_sgn (const cu_mpz_t);
__host__ __device__ int cu_mpz_cmp_si (const cu_mpz_t, long);
__host__ __device__ int cu_mpz_cmp_ui (const cu_mpz_t, unsigned long);
__host__ __device__ int cu_mpz_cmp (const cu_mpz_t, const cu_mpz_t);
__host__ __device__ int cu_mpz_cmpabs_ui (const cu_mpz_t, unsigned long);
__host__ __device__ int cu_mpz_cmpabs (const cu_mpz_t, const cu_mpz_t);
__host__ __device__ int cu_mpz_cmp_d (const cu_mpz_t, double);
__host__ __device__ int cu_mpz_cmpabs_d (const cu_mpz_t, double);

__host__ __device__ void cu_mpz_abs (cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_neg (cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_swap (cu_mpz_t, cu_mpz_t);

__host__ __device__ void cu_mpz_add_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_add (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_sub_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_ui_sub (cu_mpz_t, unsigned long, const cu_mpz_t);
__host__ __device__ void cu_mpz_sub (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ void cu_mpz_mul_si (cu_mpz_t, const cu_mpz_t, long int);
__host__ __device__ void cu_mpz_mul_ui (cu_mpz_t, const cu_mpz_t, unsigned long int);
__host__ __device__ void cu_mpz_mul (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_mul_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_addmul_ui (cu_mpz_t, const cu_mpz_t, unsigned long int);
__host__ __device__ void cu_mpz_addmul (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_submul_ui (cu_mpz_t, const cu_mpz_t, unsigned long int);
__host__ __device__ void cu_mpz_submul (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ void cu_mpz_cdiv_qr (cu_mpz_t, cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_fdiv_qr (cu_mpz_t, cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_tdiv_qr (cu_mpz_t, cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_cdiv_q (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_fdiv_q (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_tdiv_q (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_cdiv_r (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_fdiv_r (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_tdiv_r (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ void cu_mpz_cdiv_q_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_fdiv_q_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_tdiv_q_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_cdiv_r_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_fdiv_r_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_tdiv_r_2exp (cu_mpz_t, const cu_mpz_t, cu_mp_bitcnt_t);

__host__ __device__ void cu_mpz_mod (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ void cu_mpz_divexact (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ int cu_mpz_divisible_p (const cu_mpz_t, const cu_mpz_t);
__host__ __device__ int cu_mpz_congruent_p (const cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ unsigned long cu_mpz_cdiv_qr_ui (cu_mpz_t, cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_fdiv_qr_ui (cu_mpz_t, cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_tdiv_qr_ui (cu_mpz_t, cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_cdiv_q_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_fdiv_q_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_tdiv_q_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_cdiv_r_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_fdiv_r_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_tdiv_r_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_cdiv_ui (const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_fdiv_ui (const cu_mpz_t, unsigned long);
__host__ __device__ unsigned long cu_mpz_tdiv_ui (const cu_mpz_t, unsigned long);

__host__ __device__ unsigned long cu_mpz_mod_ui (cu_mpz_t, const cu_mpz_t, unsigned long);

__host__ __device__ void cu_mpz_divexact_ui (cu_mpz_t, const cu_mpz_t, unsigned long);

__host__ __device__ int cu_mpz_divisible_ui_p (const cu_mpz_t, unsigned long);

__host__ __device__ unsigned long cu_mpz_gcd_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_gcd (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_gcdext (cu_mpz_t, cu_mpz_t, cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_lcm_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_lcm (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ int cu_mpz_invert (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ void cu_mpz_sqrtrem (cu_mpz_t, cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_sqrt (cu_mpz_t, const cu_mpz_t);
__host__ __device__ int cu_mpz_perfect_square_p (const cu_mpz_t);

__host__ __device__ void cu_mpz_pow_ui (cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_ui_pow_ui (cu_mpz_t, unsigned long, unsigned long);
__host__ __device__ void cu_mpz_powm (cu_mpz_t, const cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_powm_ui (cu_mpz_t, const cu_mpz_t, unsigned long, const cu_mpz_t);

__host__ __device__ void cu_mpz_rootrem (cu_mpz_t, cu_mpz_t, const cu_mpz_t, unsigned long);
__host__ __device__ int cu_mpz_root (cu_mpz_t, const cu_mpz_t, unsigned long);

__host__ __device__ void cu_mpz_fac_ui (cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_2fac_ui (cu_mpz_t, unsigned long);
__host__ __device__ void cu_mpz_mfac_uiui (cu_mpz_t, unsigned long, unsigned long);
__host__ __device__ void cu_mpz_bin_uiui (cu_mpz_t, unsigned long, unsigned long);

__host__ __device__ int cu_mpz_probab_prime_p (const cu_mpz_t, int);

__host__ __device__ int cu_mpz_tstbit (const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_setbit (cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_clrbit (cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ void cu_mpz_combit (cu_mpz_t, cu_mp_bitcnt_t);

__host__ __device__ void cu_mpz_com (cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_and (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_ior (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_xor (cu_mpz_t, const cu_mpz_t, const cu_mpz_t);

__host__ __device__ cu_mp_bitcnt_t cu_mpz_popcount (const cu_mpz_t);
__host__ __device__ cu_mp_bitcnt_t cu_mpz_hamdist (const cu_mpz_t, const cu_mpz_t);
__host__ __device__ cu_mp_bitcnt_t cu_mpz_scan0 (const cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ cu_mp_bitcnt_t cu_mpz_scan1 (const cu_mpz_t, cu_mp_bitcnt_t);

__host__ __device__ int cu_mpz_fits_slong_p (const cu_mpz_t);
__host__ __device__ int cu_mpz_fits_ulong_p (const cu_mpz_t);
__host__ __device__ int cu_mpz_fits_sint_p (const cu_mpz_t);
__host__ __device__ int cu_mpz_fits_uint_p (const cu_mpz_t);
__host__ __device__ int cu_mpz_fits_sshort_p (const cu_mpz_t);
__host__ __device__ int cu_mpz_fits_ushort_p (const cu_mpz_t);
__host__ __device__ long int cu_mpz_get_si (const cu_mpz_t);
__host__ __device__ unsigned long int cu_mpz_get_ui (const cu_mpz_t);
__host__ __device__ double cu_mpz_get_d (const cu_mpz_t);
__host__ __device__ size_t cu_mpz_size (const cu_mpz_t);
__host__ __device__ cu_mp_limb_t cu_mpz_getlimbn (const cu_mpz_t, cu_mp_size_t);

__host__ __device__ void cu_mpz_realloc2 (cu_mpz_t, cu_mp_bitcnt_t);
__host__ __device__ mp_srcptr cu_mpz_limbs_read (cu_mpz_srcptr);
__host__ __device__ mp_ptr cu_mpz_limbs_modify (cu_mpz_t, cu_mp_size_t);
__host__ __device__ mp_ptr cu_mpz_limbs_write (cu_mpz_t, cu_mp_size_t);
__host__ __device__ void cu_mpz_limbs_finish (cu_mpz_t, cu_mp_size_t);
__host__ __device__ cu_mpz_srcptr cu_mpz_roinit_n (cu_mpz_t, mp_srcptr, cu_mp_size_t);

#define MPZ_ROINIT_N(xp, xs) {{0, (xs),(xp) }}

__host__ __device__ void cu_mpz_set_si (cu_mpz_t, signed long int);
__host__ __device__ void cu_mpz_set_ui (cu_mpz_t, unsigned long int);
__host__ __device__ void cu_mpz_set (cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_set_d (cu_mpz_t, double);

__host__ __device__ void cu_mpz_init_set_si (cu_mpz_t, signed long int);
__host__ __device__ void cu_mpz_init_set_ui (cu_mpz_t, unsigned long int);
__host__ __device__ void cu_mpz_init_set (cu_mpz_t, const cu_mpz_t);
__host__ __device__ void cu_mpz_init_set_d (cu_mpz_t, double);

__host__ __device__ size_t cu_mpz_sizeinbase (const cu_mpz_t, int);
__host__ __device__ char *cu_mpz_get_str (char *, int, const cu_mpz_t);
int cu_mpz_set_str (cu_mpz_t, const char *, int);
int cu_mpz_init_set_str (cu_mpz_t, const char *, int);

/* This long list taken from gmp.h. */
/* For reference, "defined(EOF)" cannot be used here.  In g++ 2.95.4,
   <iostream> defines EOF but not FILE.  */
#if defined (FILE)                                              \
  || defined (H_STDIO)                                          \
  || defined (_H_STDIO)               /* AIX */                 \
  || defined (_STDIO_H)               /* glibc, Sun, SCO */     \
  || defined (_STDIO_H_)              /* BSD, OSF */            \
  || defined (__STDIO_H)              /* Borland */             \
  || defined (__STDIO_H__)            /* IRIX */                \
  || defined (_STDIO_INCLUDED)        /* HPUX */                \
  || defined (__dj_include_stdio_h_)  /* DJGPP */               \
  || defined (_FILE_DEFINED)          /* Microsoft */           \
  || defined (__STDIO__)              /* Apple MPW MrC */       \
  || defined (_MSL_STDIO_H)           /* Metrowerks */          \
  || defined (_STDIO_H_INCLUDED)      /* QNX4 */		\
  || defined (_ISO_STDIO_ISO_H)       /* Sun C++ */		\
  || defined (__STDIO_LOADED)         /* VMS */			\
  || defined (_STDIO)                 /* HPE NonStop */         \
  || defined (__DEFINED_FILE)         /* musl */
size_t cu_mpz_out_str (FILE *, int, const cu_mpz_t);
#endif

__host__ __device__ void cu_mpz_import (cu_mpz_t, size_t, int, size_t, int, size_t, const void *);
__host__ __device__ void *cu_mpz_export (void *, size_t *, int, size_t, int, size_t, const cu_mpz_t);

#if defined (__cplusplus)
}
#endif

/* ---- per-thread bump arena (see tools/cudafy_minigmp.py preamble) ---- */
extern __managed__ char   *mpc_cuda_arena_base;
extern __managed__ size_t  mpc_cuda_arena_slab;
extern __managed__ size_t *mpc_cuda_arena_top;
__host__ __device__ void *mpc_cuda_dev_alloc (size_t);
__host__ __device__ void  mpc_cuda_dev_free (void *);
__host__ __device__ void *mpc_cuda_dev_realloc (void *, size_t, size_t);
__device__ void mpc_cuda_arena_reset (void);


/* ---- gmp.h shim stand-ins (randstate / mpf_t / mpq_t) ---- */
/* shim: MPC's #include "gmp.h" -> CUDA mini-gmp + RODATA helper */
#ifndef CU_MPFR_RODATA
# ifdef __CUDA_ARCH__
#  define CU_MPFR_RODATA __device__
# else
#  define CU_MPFR_RODATA
# endif
#endif

/* mini-gmp has no random functions: MPFR/MPC need cu_gmp_randstate_t declared. */
#ifndef cu_gmp_randstate_t
typedef long int cu___gmp_randstate_struct;
typedef cu___gmp_randstate_struct cu_gmp_randstate_t[1];
#endif

/* mini-gmp provides neither cu_mpf_t (GMP float) nor cu_mpq_t.  MPC declares a few
   conversion prototypes (cu_mpc_set_f/_q, ...) that we do not build for the
   device; provide minimal type stand-ins so the public header parses. */
#ifndef __MPF_STRUCT_DEFINED
#define __MPF_STRUCT_DEFINED
typedef struct { int _mp_prec; int _mp_size; long _mp_exp; cu_mp_limb_t *_mp_d; } cu___mpf_struct;
typedef cu___mpf_struct cu_mpf_t[1];
typedef cu___mpf_struct *cu_mpf_ptr;
typedef const cu___mpf_struct *cu_mpf_srcptr;
typedef struct { cu___mpz_struct _mp_num; cu___mpz_struct _mp_den; } cu___mpq_struct;
typedef cu___mpq_struct cu_mpq_t[1];
typedef cu___mpq_struct *cu_mpq_ptr;
typedef const cu___mpq_struct *cu_mpq_srcptr;
#endif

#endif /* CU_MPC_CUDA_GMP_H */
