/* Auto-generated by tools/make_umbrella.py -- do NOT edit by hand.
 * Fully cu_/CU_-namespaced public header: every type, enum constant,
 * macro and include guard is prefixed so this coexists with the system
 * <gmp.h>/<mpfr.h>/<mpc.h> in the SAME translation unit. */
/* CUDA-adapted from MPFR by tools/cudafy_mpfr.py. */
/* mpfr.h -- Include file for mpfr.

Copyright 1999-2025 Free Software Foundation, Inc.
Contributed by the Pascaline and Caramba projects, INRIA.

This file is part of the GNU MPFR Library.

The GNU MPFR Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MPFR Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MPFR Library; see the file COPYING.LESSER.
If not, see <https://www.gnu.org/licenses/>. */

#ifndef CU_MPC_CUDA_MPFR_H
#define CU_MPC_CUDA_MPFR_H

/* Define MPFR version number */
#define CU_MPFR_VERSION_MAJOR 4
#define CU_MPFR_VERSION_MINOR 2
#define CU_MPFR_VERSION_PATCHLEVEL 2
#define CU_MPFR_VERSION_STRING "4.2.2"

/* User macros:
   CU_MPFR_USE_FILE:        Define it to make MPFR define functions dealing
                         with FILE* (auto-detect).
   CU_MPFR_USE_INTMAX_T:    Define it to make MPFR define functions dealing
                         with intmax_t (auto-detect).
   CU_MPFR_USE_VA_LIST:     Define it to make MPFR define functions dealing
                         with va_list (auto-detect).
   CU_MPFR_USE_C99_FEATURE: Define it to 1 to make MPFR support C99-feature
                         (auto-detect), to 0 to bypass the detection.
   CU_MPFR_USE_EXTENSION:   Define it to make MPFR use GCC extension to
                         reduce warnings.
   CU_MPFR_USE_NO_MACRO:    Define it to make MPFR remove any overriding
                         function macro.
*/

/* Macros dealing with MPFR VERSION */
#define CU_MPFR_VERSION_NUM(a,b,c) (((a) << 16L) | ((b) << 8) | (c))
#define CU_MPFR_VERSION \
CU_MPFR_VERSION_NUM(CU_MPFR_VERSION_MAJOR,CU_MPFR_VERSION_MINOR,CU_MPFR_VERSION_PATCHLEVEL)

#ifndef CU_MPFR_USE_MINI_GMP
#include "mpc_cuda/cu_gmp.h"
#else
#include "mpc_cuda/cu_gmp.h"
#endif

/* Avoid some problems with macro expansion if the user defines macros
   with the same name as keywords. By convention, identifiers and macro
   names starting with mpfr_ are reserved by MPFR. */
typedef void            cu_mpfr_void;
typedef int             cu_mpfr_int;
typedef unsigned int    cu_mpfr_uint;
typedef long            cu_mpfr_long;
typedef unsigned long   cu_mpfr_ulong;
typedef size_t          cu_mpfr_size_t;

/* Global (possibly TLS) flags. Might also be used in an cu_mpfr_t in the
   future (there would be room as cu_mpfr_sign_t just needs 1 byte).
   TODO: The tests currently assume that the flags fits in an unsigned int;
   this should be cleaned up, e.g. by defining a function that outputs the
   flags as a string or by using the flags_out function (from tests/tests.c
   directly). */
typedef unsigned int    cu_mpfr_flags_t;

/* Flags macros (in the public API) */
#define CU_MPFR_FLAGS_UNDERFLOW 1
#define CU_MPFR_FLAGS_OVERFLOW 2
#define CU_MPFR_FLAGS_NAN 4
#define CU_MPFR_FLAGS_INEXACT 8
#define CU_MPFR_FLAGS_ERANGE 16
#define CU_MPFR_FLAGS_DIVBY0 32
#define CU_MPFR_FLAGS_ALL (CU_MPFR_FLAGS_UNDERFLOW | \
                        CU_MPFR_FLAGS_OVERFLOW  | \
                        CU_MPFR_FLAGS_NAN       | \
                        CU_MPFR_FLAGS_INEXACT   | \
                        CU_MPFR_FLAGS_ERANGE    | \
                        CU_MPFR_FLAGS_DIVBY0)

/* Definition of rounding modes (DON'T USE CU_MPFR_RNDNA!).
   Warning! Changing the contents of this enum should be seen as an
   interface change since the old and the new types are not compatible
   (the integer type compatible with the enumerated type can even change,
   see ISO C99, 6.7.2.2#4), and in Makefile.am, AGE should be set to 0.

   CU_MPFR_RNDU must appear just before CU_MPFR_RNDD (see
   CU_MPFR_IS_RNDUTEST_OR_RNDDNOTTEST in mpfr-impl.h).

   If you change the order of the rounding modes, please update the routines
   in texceptions.c which assume 0=RNDN, 1=RNDZ, 2=RNDU, 3=RNDD, 4=RNDA.
*/
typedef enum {
  CU_MPFR_RNDN=0,  /* round to nearest, with ties to even */
  CU_MPFR_RNDZ,    /* round toward zero */
  CU_MPFR_RNDU,    /* round toward +Inf */
  CU_MPFR_RNDD,    /* round toward -Inf */
  CU_MPFR_RNDA,    /* round away from zero */
  CU_MPFR_RNDF,    /* faithful rounding */
  CU_MPFR_RNDNA=-1 /* round to nearest, with ties away from zero (cu_mpfr_round) */
} cu_mpfr_rnd_t;

/* kept for compatibility with MPFR 2.4.x and before */
#define CU_GMP_RNDN CU_MPFR_RNDN
#define CU_GMP_RNDZ CU_MPFR_RNDZ
#define CU_GMP_RNDU CU_MPFR_RNDU
#define CU_GMP_RNDD CU_MPFR_RNDD

/* The _MPFR_PREC_FORMAT and _MPFR_EXP_FORMAT values are automatically
   defined below. You MUST NOT force a value (this will break the ABI),
   possibly except for a very particular use, in which case you also need
   to rebuild the MPFR library with the chosen values; do not install this
   rebuilt library in a path that is searched by default, otherwise this
   will break applications that are dynamically linked with MPFR.

   Using non-default values is not guaranteed to work.

   Note: With the following default choices for _MPFR_PREC_FORMAT and
   _MPFR_EXP_FORMAT, cu_mpfr_exp_t will be the same as [cu_mp_exp_t] (at least
   up to GMP 6). */

/* Define precision: 1 (short), 2 (int) or 3 (long).
   DON'T FORCE A VALUE (see above). */
#ifndef _MPFR_PREC_FORMAT
# if __CU_GMP_MP_SIZE_T_INT
#  define _MPFR_PREC_FORMAT 2
# else
#  define _MPFR_PREC_FORMAT 3
# endif
#endif

/* Define exponent: 1 (short), 2 (int), 3 (long) or 4 (intmax_t).
   DON'T FORCE A VALUE (see above). */
#ifndef _MPFR_EXP_FORMAT
# define _MPFR_EXP_FORMAT _MPFR_PREC_FORMAT
#endif

#if _MPFR_PREC_FORMAT > _MPFR_EXP_FORMAT
# error "cu_mpfr_prec_t must not be larger than cu_mpfr_exp_t"
#endif

/* Let's make cu_mpfr_prec_t signed in order to avoid problems due to the
   usual arithmetic conversions when mixing cu_mpfr_prec_t and cu_mpfr_exp_t
   in an expression (for error analysis) if casts are forgotten.
   Note: cu_mpfr_prec_t is currently limited to "long". This means that
   under MS Windows, the precisions are limited to about 2^31; however,
   these are already huge precisions, probably sufficient in practice
   on this platform. */
#if   _MPFR_PREC_FORMAT == 1
typedef short cu_mpfr_prec_t;
typedef unsigned short cu_mpfr_uprec_t;
#elif _MPFR_PREC_FORMAT == 2
typedef int   cu_mpfr_prec_t;
typedef unsigned int   cu_mpfr_uprec_t;
#elif _MPFR_PREC_FORMAT == 3
typedef long  cu_mpfr_prec_t;
typedef unsigned long  cu_mpfr_uprec_t;
#else
# error "Invalid MPFR Prec format"
#endif

/* Definition of precision limits without needing <limits.h> */
/* Note: The casts allows the expression to yield the wanted behavior
   for _MPFR_PREC_FORMAT == 1 (due to integer promotion rules). We
   also make sure that CU_MPFR_PREC_MIN and CU_MPFR_PREC_MAX have a signed
   integer type. The "- 256" allows more security, avoiding some
   integer overflows in extreme cases; ideally it should be useless. */
#define CU_MPFR_PREC_MIN 1
#define CU_MPFR_PREC_MAX ((cu_mpfr_prec_t) ((((cu_mpfr_uprec_t) -1) >> 1) - 256))

/* Definition of sign */
typedef int          cu_mpfr_sign_t;

/* Definition of the exponent. _MPFR_EXP_FORMAT must be large enough
   so that cu_mpfr_exp_t has at least 32 bits. */
#if   _MPFR_EXP_FORMAT == 1
typedef short cu_mpfr_exp_t;
typedef unsigned short cu_mpfr_uexp_t;
#elif _MPFR_EXP_FORMAT == 2
typedef int cu_mpfr_exp_t;
typedef unsigned int cu_mpfr_uexp_t;
#elif _MPFR_EXP_FORMAT == 3
typedef long cu_mpfr_exp_t;
typedef unsigned long cu_mpfr_uexp_t;
#elif _MPFR_EXP_FORMAT == 4
/* Note: in this case, intmax_t and uintmax_t must be defined before
   the inclusion of mpfr.h (we do not include <stdint.h> here due to
   potential issues with non-ISO implementations, on which there are
   alternative ways to define these types).
   In all known implementations, intmax_t has exactly 64 bits and is
   equivalent to long long when defined, but when long has 64 bits,
   it may be defined as long by <stdint.h> for better portability
   with old compilers, thus offers more flexibility than long long.
   This may change in the future.
   This _MPFR_EXP_FORMAT value is currently not supported since the
   MPFR code assumes that cu_mpfr_exp_t fits in a long. Some examples
   of problematic code can be obtained with:
     grep -E 'cu_mpfr_cmp_[su]i *\(.*cu___gmpfr_em' *.c
*/
typedef intmax_t cu_mpfr_exp_t;
typedef uintmax_t cu_mpfr_uexp_t;
#else
# error "Invalid MPFR Exp format"
#endif

/* Definition of the standard exponent limits */
#define CU_MPFR_EMAX_DEFAULT ((cu_mpfr_exp_t) (((cu_mpfr_ulong) 1 << 30) - 1))
#define CU_MPFR_EMIN_DEFAULT (-(CU_MPFR_EMAX_DEFAULT))

/* DON'T USE THIS! (For MPFR-public macros only, see below.)
   The cu_mpfr_sgn macro uses the fact that __CU_MPFR_EXP_NAN and __CU_MPFR_EXP_ZERO
   are the smallest values. For a n-bit type, EXP_MAX is 2^(n-1)-1,
   EXP_ZERO is 1-2^(n-1), EXP_NAN is 2-2^(n-1), EXP_INF is 3-2^(n-1).
   This may change in the future. MPFR code should not be based on these
   representations (but if this is absolutely needed, protect the code
   with a static assertion). */
#define __CU_MPFR_EXP_MAX ((cu_mpfr_exp_t) (((cu_mpfr_uexp_t) -1) >> 1))
#define __CU_MPFR_EXP_NAN  (1 - __CU_MPFR_EXP_MAX)
#define __CU_MPFR_EXP_ZERO (0 - __CU_MPFR_EXP_MAX)
#define __CU_MPFR_EXP_INF  (2 - __CU_MPFR_EXP_MAX)

/* Definition of the main structure */
typedef struct {
  cu_mpfr_prec_t  _mpfr_prec;
  cu_mpfr_sign_t  _mpfr_sign;
  cu_mpfr_exp_t   _mpfr_exp;
  cu_mp_limb_t   *_mpfr_d;
} cu___mpfr_struct;

/* Compatibility with previous types of MPFR */
#ifndef cu_mp_rnd_t
# define cu_mp_rnd_t  cu_mpfr_rnd_t
#endif
#ifndef cu_mp_prec_t
# define cu_mp_prec_t cu_mpfr_prec_t
#endif

/*
   The represented number is
      _sign*(_d[k-1]/B+_d[k-2]/B^2+...+_d[0]/B^k)*2^_exp
   where k=ceil(_mp_prec/CU_GMP_NUMB_BITS) and B=2^CU_GMP_NUMB_BITS.

   For the msb (most significant bit) normalized representation, we must have
      _d[k-1]>=B/2, unless the number is singular.

   We must also have the last k*CU_GMP_NUMB_BITS-_prec bits set to zero.
*/

typedef cu___mpfr_struct cu_mpfr_t[1];
typedef cu___mpfr_struct *cu_mpfr_ptr;
typedef const cu___mpfr_struct *cu_mpfr_srcptr;

/* For those who need a direct and fast access to the sign field.
   However, it is not in the API, thus use it at your own risk: it
   might not be supported, or change name, in further versions!
   Unfortunately, it must be defined here (instead of MPFR's internal
   header file mpfr-impl.h) because it is used by some macros below.
*/
#define CU_MPFR_SIGN(x) ((x)->_mpfr_sign)

/* Custom interface */
typedef enum {
  CU_MPFR_NAN_KIND     = 0,
  CU_MPFR_INF_KIND     = 1,
  CU_MPFR_ZERO_KIND    = 2,
  CU_MPFR_REGULAR_KIND = 3
} cu_mpfr_kind_t;

/* Free cache policy */
typedef enum {
  CU_MPFR_FREE_LOCAL_CACHE  = 1,  /* 1 << 0 */
  CU_MPFR_FREE_GLOBAL_CACHE = 2   /* 1 << 1 */
} cu_mpfr_free_cache_t;

/* GMP defines:
    + size_t:                Standard size_t
    + __CU_GMP_NOTHROW          For C++: can't throw .
    + __CU_GMP_EXTERN_INLINE    Attribute for inline function.
    + __CU_GMP_DECLSPEC_EXPORT  compiling to go into a DLL
    + __CU_GMP_DECLSPEC_IMPORT  compiling to go into a application
*/
/* Extra MPFR defines */
#define __CU_MPFR_SENTINEL_ATTR
#if defined (__GNUC__)
# if __GNUC__ >= 4
#  undef __CU_MPFR_SENTINEL_ATTR
#  define __CU_MPFR_SENTINEL_ATTR __attribute__ ((__sentinel__))
# endif
#endif

/* If the user hasn't requested his/her preference
   and if the intention of support by the compiler is C99
   and if the compiler is known to support the C99 feature
   then we can auto-detect the C99 support as OK.
   __GNUC__ is used to detect GNU-C, ICC & CLANG compilers.
   Currently we need only variadic macros, and they are present
   since GCC >= 3. We don't test library version since we don't
   use any feature present in the library too (except intmax_t,
   but they use another detection).*/
#ifndef CU_MPFR_USE_C99_FEATURE
# if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#  if defined (__GNUC__)
#   if __GNUC__ >= 3
#    define CU_MPFR_USE_C99_FEATURE 1
#   endif
#  endif
# endif
# ifndef CU_MPFR_USE_C99_FEATURE
#  define CU_MPFR_USE_C99_FEATURE 0
# endif
#endif

/* Support for WINDOWS Dll:
   Check if we are inside a MPFR build, and if so export the functions.
   Otherwise does the same thing as GMP */
#if defined(__CU_MPFR_WITHIN_MPFR) && __CU_GMP_LIBGMP_DLL
# define __CU_MPFR_DECLSPEC __CU_GMP_DECLSPEC_EXPORT
#else
# ifndef __CU_GMP_DECLSPEC
#  define __CU_GMP_DECLSPEC
# endif
# define __CU_MPFR_DECLSPEC __CU_GMP_DECLSPEC
#endif

/* Use CU_MPFR_DEPRECATED to mark MPFR functions, types or variables as
   deprecated. Code inspired by Apache Subversion's svn_types.h file.
   For compatibility with MSVC, CU_MPFR_DEPRECATED must be put before
__host__ __device__    __CU_MPFR_DECLSPEC (not at the end of the function declaration as
   documented in the GCC manual); GCC does not seem to care.
   Moreover, in order to avoid a warning when testing such functions,
   do something like:
     +------------------------------------------
     |#ifndef _MPFR_NO_DEPRECATED_funcname
     |CU_MPFR_DEPRECATED
     |#endif
     |__CU_MPFR_DECLSPEC int cu_mpfr_funcname (...);
     +------------------------------------------
   and in the corresponding test program:
     +------------------------------------------
     |#define _MPFR_NO_DEPRECATED_funcname
     |#include "mpfr-test.h"
     +------------------------------------------
*/
#if defined(__GNUC__) && \
  (__GNUC__ >= 4 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
# define CU_MPFR_DEPRECATED __attribute__ ((__deprecated__))
#elif defined(_MSC_VER) && _MSC_VER >= 1300
# define CU_MPFR_DEPRECATED __declspec(deprecated)
#else
# define CU_MPFR_DEPRECATED
#endif
/* TODO: Also define CU_MPFR_EXPERIMENTAL for experimental functions?
   See SVN_EXPERIMENTAL in Subversion 1.9+ as an example:
   __attribute__((__warning__("..."))) can be used with GCC 4.3.1+ but
   not __llvm__, and __declspec(deprecated("...")) can be used with
   MSC as above. */

/* ICC up to 19.1.3.304 at least declares itself as interoperable with
   GCC 4.9, but does not support the returns_nonnull attribute, thus
   outputs warning #1292. This minor issue has been reported in 2019-04:
   https://community.intel.com/t5/Intel-C-Compiler/Missing-support-for-returns-nonnull-attribute/td-p/1183013 */
#if defined(__GNUC__) && \
  (__GNUC__ >= 5 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 9))
# define CU_MPFR_RETURNS_NONNULL __attribute__ ((__returns_nonnull__))
#else
# define CU_MPFR_RETURNS_NONNULL
#endif

/* Note: In order to be declared, some functions need a specific
   system header to be included *before* "mpfr.h". If the user
   forgets to include the header, the MPFR function prototype in
   the user object file is not correct. To avoid wrong results,
   we raise a linker error in that case by changing their internal
   name in the library (prefixed by __gmpfr instead of mpfr). See
   the lines of the form "#define cu_mpfr_xxx cu___gmpfr_xxx" below. */

#if defined (__cplusplus)
extern "C" {
#endif

__host__ __device__ __CU_MPFR_DECLSPEC CU_MPFR_RETURNS_NONNULL const char * cu_mpfr_get_version (void);
__host__ __device__ __CU_MPFR_DECLSPEC CU_MPFR_RETURNS_NONNULL const char * cu_mpfr_get_patches (void);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_buildopt_tls_p          (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_buildopt_float128_p     (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_buildopt_decimal_p      (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_buildopt_gmpinternals_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_buildopt_sharedcache_p  (void);
__host__ __device__ __CU_MPFR_DECLSPEC CU_MPFR_RETURNS_NONNULL const char *
  cu_mpfr_buildopt_tune_case (void);

__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emin     (void);
__host__ __device__ __CU_MPFR_DECLSPEC int        cu_mpfr_set_emin     (cu_mpfr_exp_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emin_min (void);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emin_max (void);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emax     (void);
__host__ __device__ __CU_MPFR_DECLSPEC int        cu_mpfr_set_emax     (cu_mpfr_exp_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emax_min (void);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_emax_max (void);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_default_rounding_mode (cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_rnd_t cu_mpfr_get_default_rounding_mode (void);
__host__ __device__ __CU_MPFR_DECLSPEC const char * cu_mpfr_print_rnd_mode (cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_flags (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_underflow (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_overflow (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_divby0 (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_nanflag (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_inexflag (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear_erangeflag (void);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_underflow (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_overflow (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_divby0 (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_nanflag (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_inexflag (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_erangeflag (void);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_underflow_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_overflow_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_divby0_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_nanflag_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_inexflag_p (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_erangeflag_p (void);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_flags_clear (cu_mpfr_flags_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_flags_set (cu_mpfr_flags_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_flags_t cu_mpfr_flags_test (cu_mpfr_flags_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_flags_t cu_mpfr_flags_save (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_flags_restore (cu_mpfr_flags_t,
                                         cu_mpfr_flags_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_check_range (cu_mpfr_ptr, int, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_init2 (cu_mpfr_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_init (cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_clear (cu_mpfr_ptr);

__host__ __device__ __CU_MPFR_DECLSPEC void
  cu_mpfr_inits2 (cu_mpfr_prec_t, cu_mpfr_ptr, ...) __CU_MPFR_SENTINEL_ATTR;
__host__ __device__ __CU_MPFR_DECLSPEC void
  cu_mpfr_inits (cu_mpfr_ptr, ...) __CU_MPFR_SENTINEL_ATTR;
__host__ __device__ __CU_MPFR_DECLSPEC void
  cu_mpfr_clears (cu_mpfr_ptr, ...) __CU_MPFR_SENTINEL_ATTR;

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_prec_round (cu_mpfr_ptr, cu_mpfr_prec_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_can_round (cu_mpfr_srcptr, cu_mpfr_exp_t, cu_mpfr_rnd_t,
                                    cu_mpfr_rnd_t, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_prec_t cu_mpfr_min_prec (cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_exp (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_exp (cu_mpfr_ptr, cu_mpfr_exp_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_prec_t cu_mpfr_get_prec (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_prec (cu_mpfr_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_prec_raw (cu_mpfr_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_default_prec (cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_prec_t cu_mpfr_get_default_prec (void);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_d (cu_mpfr_ptr, double, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_flt (cu_mpfr_ptr, float, cu_mpfr_rnd_t);
#ifdef CU_MPFR_WANT_DECIMAL_FLOATS
/* _Decimal64 is not defined in C++,
   cf https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51364 */
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_decimal64 (cu_mpfr_ptr, _Decimal64, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_decimal128 (cu_mpfr_ptr, _Decimal128, cu_mpfr_rnd_t);
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_ld (cu_mpfr_ptr, long double, cu_mpfr_rnd_t);
#ifdef CU_MPFR_WANT_FLOAT128
/* The user is free to define cu_mpfr_float128 as another equivalent type,
   such as __float128 if this one is supported by the current compiler
   but _Float128 isn't. */
# ifndef cu_mpfr_float128
#  define cu_mpfr_float128 _Float128
# endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_float128 (cu_mpfr_ptr, cu_mpfr_float128, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_float128 cu_mpfr_get_float128 (cu_mpfr_srcptr, cu_mpfr_rnd_t);
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_z (cu_mpfr_ptr, cu_mpz_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_z_2exp (cu_mpfr_ptr, cu_mpz_srcptr, cu_mpfr_exp_t,
                                     cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_nan (cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_inf (cu_mpfr_ptr, int);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_set_zero (cu_mpfr_ptr, int);

#ifndef CU_MPFR_USE_MINI_GMP
  /* mini-gmp does not provide cu_mpf_t, we disable the following functions */
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_f (cu_mpfr_ptr, cu_mpf_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_f (cu_mpfr_srcptr, cu_mpf_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_get_f (cu_mpf_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_si (cu_mpfr_ptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_ui (cu_mpfr_ptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_si_2exp (cu_mpfr_ptr, long, cu_mpfr_exp_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_ui_2exp (cu_mpfr_ptr, unsigned long, cu_mpfr_exp_t,
                                      cu_mpfr_rnd_t);
#ifndef CU_MPFR_USE_MINI_GMP
  /* mini-gmp does not provide cu_mpq_t, we disable the following functions */
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_q (cu_mpfr_ptr, cu_mpq_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_q (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpq_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_q (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpq_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add_q (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpq_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub_q (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpq_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_q (cu_mpfr_srcptr, cu_mpq_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_get_q (cu_mpq_ptr q, cu_mpfr_srcptr f);
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_str (cu_mpfr_ptr, const char *, int, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_init_set_str (cu_mpfr_ptr, const char *, int,
                                       cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set4 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t, int);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_abs (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_neg (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_signbit (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_setsign (cu_mpfr_ptr, cu_mpfr_srcptr, int, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_copysign (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                   cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_get_z_2exp (cu_mpz_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC float cu_mpfr_get_flt (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC double cu_mpfr_get_d (cu_mpfr_srcptr, cu_mpfr_rnd_t);
#ifdef CU_MPFR_WANT_DECIMAL_FLOATS
__host__ __device__ __CU_MPFR_DECLSPEC _Decimal64 cu_mpfr_get_decimal64 (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC _Decimal128 cu_mpfr_get_decimal128 (cu_mpfr_srcptr, cu_mpfr_rnd_t);
#endif
__host__ __device__ __CU_MPFR_DECLSPEC long double cu_mpfr_get_ld (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC double cu_mpfr_get_d1 (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC double cu_mpfr_get_d_2exp (long*, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC long double cu_mpfr_get_ld_2exp (long*, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_frexp (cu_mpfr_exp_t*, cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC long cu_mpfr_get_si (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC unsigned long cu_mpfr_get_ui (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC size_t cu_mpfr_get_str_ndigits (int, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC char * cu_mpfr_get_str (char*, cu_mpfr_exp_t*, int, size_t,
                                     cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_get_z (cu_mpz_ptr z, cu_mpfr_srcptr f, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_free_str (char *);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_urandom (cu_mpfr_ptr, cu_gmp_randstate_t, cu_mpfr_rnd_t);
#ifndef _MPFR_NO_DEPRECATED_GRANDOM /* for the test of this function */
CU_MPFR_DEPRECATED
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_grandom (cu_mpfr_ptr, cu_mpfr_ptr, cu_gmp_randstate_t,
                                  cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_nrandom (cu_mpfr_ptr, cu_gmp_randstate_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_erandom (cu_mpfr_ptr, cu_gmp_randstate_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_urandomb (cu_mpfr_ptr, cu_gmp_randstate_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_nextabove (cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_nextbelow (cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_nexttoward (cu_mpfr_ptr, cu_mpfr_srcptr);

#ifndef CU_MPFR_USE_MINI_GMP
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_printf (const char*, ...);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_asprintf (char**, const char*, ...);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sprintf (char*, const char*, ...);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_snprintf (char*, size_t, const char*, ...);
#endif

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_powr (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_compound_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ui_pow_ui (cu_mpfr_ptr, unsigned long, unsigned long,
                                    cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ui_pow (cu_mpfr_ptr, unsigned long, cu_mpfr_srcptr,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow_z (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpz_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sqrt (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sqrt_ui (cu_mpfr_ptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rec_sqrt (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ui_sub (cu_mpfr_ptr, unsigned long, cu_mpfr_srcptr,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ui_div (cu_mpfr_ptr, unsigned long, cu_mpfr_srcptr,
                                 cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_si_sub (cu_mpfr_ptr, long, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_si_div (cu_mpfr_ptr, long, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add_d (cu_mpfr_ptr, cu_mpfr_srcptr, double, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub_d (cu_mpfr_ptr, cu_mpfr_srcptr, double, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_d_sub (cu_mpfr_ptr, double, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_d (cu_mpfr_ptr, cu_mpfr_srcptr, double, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_d (cu_mpfr_ptr, cu_mpfr_srcptr, double, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_d_div (cu_mpfr_ptr, double, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sqr (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_const_pi (cu_mpfr_ptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_const_log2 (cu_mpfr_ptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_const_euler (cu_mpfr_ptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_const_catalan (cu_mpfr_ptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_agm (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log2 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log10 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log1p (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log2p1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log10p1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_log_ui (cu_mpfr_ptr, unsigned long, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_exp (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_exp2 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_exp10 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_expm1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_exp2m1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_exp10m1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_eint (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_li2 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp  (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp3 (cu_mpfr_srcptr, cu_mpfr_srcptr, int);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_d (cu_mpfr_srcptr, double);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_ld (cu_mpfr_srcptr, long double);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_ui (cu_mpfr_srcptr, unsigned long);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_si (cu_mpfr_srcptr, long);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_ui_2exp (cu_mpfr_srcptr, unsigned long, cu_mpfr_exp_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_si_2exp (cu_mpfr_srcptr, long, cu_mpfr_exp_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmpabs (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmpabs_ui (cu_mpfr_srcptr, unsigned long);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_reldiff (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                   cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_eq (cu_mpfr_srcptr, cu_mpfr_srcptr, unsigned long);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sgn (cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_2exp (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                   cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_2exp (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                   cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_2ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                  cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_2ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                  cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_2si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_2si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_roundeven (cu_mpfr_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_round (cu_mpfr_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_trunc (cu_mpfr_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ceil (cu_mpfr_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_floor (cu_mpfr_ptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint_roundeven (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint_round (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint_trunc (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint_ceil (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rint_floor (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_frac (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_modf (cu_mpfr_ptr, cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_remquo (cu_mpfr_ptr, long*, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                 cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_remainder (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                    cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fmod (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fmod_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                  cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fmodquo (cu_mpfr_ptr, long*, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                  cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_ulong_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_slong_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_uint_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_sint_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_ushort_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_sshort_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_uintmax_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fits_intmax_p (cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_extract (cu_mpz_ptr, cu_mpfr_srcptr, unsigned int);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_swap (cu_mpfr_ptr, cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_dump (cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_nan_p (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_inf_p (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_number_p (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_integer_p (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_zero_p (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_regular_p (cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_greater_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_greaterequal_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_less_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_lessequal_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_lessgreater_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_equal_p (cu_mpfr_srcptr, cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_unordered_p (cu_mpfr_srcptr, cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atanh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_acosh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_asinh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cosh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sinh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_tanh (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sinh_cosh (cu_mpfr_ptr, cu_mpfr_ptr, cu_mpfr_srcptr,
                                    cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sech (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_csch (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_coth (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_acos (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_asin (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atan (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sin (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sin_cos (cu_mpfr_ptr, cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cos (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_tan (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atan2 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sec (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_csc (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cot (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sinu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cosu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_tanu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_acosu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_asinu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atanu (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atan2u (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_acospi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_asinpi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atanpi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_atan2pi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sinpi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cospi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_tanpi (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_hypot (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_erf (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_erfc (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cbrt (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
#ifndef _MPFR_NO_DEPRECATED_ROOT /* for the test of this function */
CU_MPFR_DEPRECATED
#endif
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_root (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                               cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rootn_ui (cu_mpfr_ptr, cu_mpfr_srcptr, unsigned long,
                                   cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_rootn_si (cu_mpfr_ptr, cu_mpfr_srcptr, long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_gamma (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_gamma_inc (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                                    cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_beta (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_lngamma (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_lgamma (cu_mpfr_ptr, int *, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_digamma (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_zeta (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_zeta_ui (cu_mpfr_ptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fac_ui (cu_mpfr_ptr, unsigned long, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_j0 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_j1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_jn (cu_mpfr_ptr, long, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_y0 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_y1 (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_yn (cu_mpfr_ptr, long, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_ai (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_min (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_max (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_dim (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mul_z (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpz_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_div_z (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpz_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_add_z (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpz_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sub_z (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpz_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_z_sub (cu_mpfr_ptr, cu_mpz_srcptr, cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_cmp_z (cu_mpfr_srcptr, cu_mpz_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fma (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                              cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fms (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                              cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fmma (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                               cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fmms (cu_mpfr_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpfr_srcptr,
                               cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_sum (cu_mpfr_ptr, const cu_mpfr_ptr *, unsigned long,
                              cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_dot (cu_mpfr_ptr, const cu_mpfr_ptr *, const cu_mpfr_ptr *,
                              unsigned long, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_free_cache (void);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_free_cache2 (cu_mpfr_free_cache_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_free_pool (void);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_mp_memory_cleanup (void);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_subnormalize (cu_mpfr_ptr, int, cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_strtofr (cu_mpfr_ptr, const char *, char **, int,
                                  cu_mpfr_rnd_t);

__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_round_nearest_away_begin (cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_round_nearest_away_end (cu_mpfr_ptr, int);

__host__ __device__ __CU_MPFR_DECLSPEC size_t cu_mpfr_custom_get_size (cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_custom_init (void *, cu_mpfr_prec_t);
__host__ __device__ __CU_MPFR_DECLSPEC CU_MPFR_RETURNS_NONNULL void *
  cu_mpfr_custom_get_significand (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC cu_mpfr_exp_t cu_mpfr_custom_get_exp (cu_mpfr_srcptr);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_custom_move (cu_mpfr_ptr, void *);
__host__ __device__ __CU_MPFR_DECLSPEC void cu_mpfr_custom_init_set (cu_mpfr_ptr, int, cu_mpfr_exp_t,
                                           cu_mpfr_prec_t, void *);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_custom_get_kind (cu_mpfr_srcptr);

__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_total_order_p (cu_mpfr_srcptr, cu_mpfr_srcptr);

#if defined (__cplusplus)
}
#endif

/* Define CU_MPFR_USE_EXTENSION to avoid "gcc -pedantic" warnings. */
#ifndef CU_MPFR_EXTENSION
# if defined(CU_MPFR_USE_EXTENSION)
#  define CU_MPFR_EXTENSION __extension__
# else
#  define CU_MPFR_EXTENSION
# endif
#endif

/* Warning! This macro doesn't work with K&R C (e.g., compare the "gcc -E"
   output with and without -traditional) and shouldn't be used internally.
   For public use only, but see the MPFR manual. */
#define CU_MPFR_DECL_INIT(_x, _p)                                        \
  CU_MPFR_EXTENSION cu_mp_limb_t cu___gmpfr_local_tab_##_x[((_p)-1)/CU_GMP_NUMB_BITS+1]; \
  CU_MPFR_EXTENSION cu_mpfr_t _x = {{(_p),1,__CU_MPFR_EXP_NAN,cu___gmpfr_local_tab_##_x}}

#if CU_MPFR_USE_C99_FEATURE
/* C99 & C11 version: functions with multiple inputs supported */
#define cu_mpfr_round_nearest_away(func, rop, ...)                         \
  (cu_mpfr_round_nearest_away_begin(rop),                                  \
   cu_mpfr_round_nearest_away_end((rop), func((rop), __VA_ARGS__, CU_MPFR_RNDN)))
#else
/* C90 version: function with one input supported */
#define cu_mpfr_round_nearest_away(func, rop, op)                          \
  (cu_mpfr_round_nearest_away_begin(rop),                                  \
   cu_mpfr_round_nearest_away_end((rop), func((rop), (op), CU_MPFR_RNDN)))
#endif

/* Fast access macros to replace function interface.
   If the user doesn't want to use the macro interface, let him make happy
   even if it produces faster and smaller code. */
#ifndef CU_MPFR_USE_NO_MACRO

/* In the implementation of these macros, we need to make sure that the
   arguments are evaluated one time exactly and that type conversion is
   done as it would be with a function. Tests should be added to ensure
   that. */

/* Prevent x from being used as an lvalue.
   Thanks to Wojtek Lerch and Tim Rentsch for the idea. */
#define CU_MPFR_VALUE_OF(x)  (0 ? (x) : (x))

/* The following macro converts the argument to cu_mpfr_srcptr, as in type
   conversion for function parameters. But it will detect disallowed
   implicit conversions, e.g. when the argument has an integer type. */
#define CU_MPFR_SRCPTR(x) ((cu_mpfr_srcptr) (0 ? (x) : (cu_mpfr_srcptr) (x)))
#define CU_MPFR_GET_SIGN(_x) CU_MPFR_VALUE_OF(CU_MPFR_SIGN(CU_MPFR_SRCPTR(_x)))

#define cu_mpfr_nan_p(_x)      (CU_MPFR_SRCPTR(_x)->_mpfr_exp == __CU_MPFR_EXP_NAN)
#define cu_mpfr_inf_p(_x)      (CU_MPFR_SRCPTR(_x)->_mpfr_exp == __CU_MPFR_EXP_INF)
#define cu_mpfr_zero_p(_x)     (CU_MPFR_SRCPTR(_x)->_mpfr_exp == __CU_MPFR_EXP_ZERO)
#define cu_mpfr_regular_p(_x)  (CU_MPFR_SRCPTR(_x)->_mpfr_exp >  __CU_MPFR_EXP_INF)

/* cu_mpfr_sgn is documented as a macro, thus the following code is fine.
   But it would be safer to regard it as a function in some future
   MPFR version. */
#define cu_mpfr_sgn(_x)                                               \
  ((_x)->_mpfr_exp < __CU_MPFR_EXP_INF ?                              \
   (cu_mpfr_nan_p (_x) ? cu_mpfr_set_erangeflag () : (cu_mpfr_void) 0), 0 : \
   CU_MPFR_SIGN (_x))

#define cu_mpfr_get_prec(_x) CU_MPFR_VALUE_OF(CU_MPFR_SRCPTR(_x)->_mpfr_prec)
#define cu_mpfr_get_exp(_x)  CU_MPFR_VALUE_OF(CU_MPFR_SRCPTR(_x)->_mpfr_exp)
/* Note: Defining cu_mpfr_get_exp() as a macro has the effect to disable
   the check that the argument is a pure FP number (done in the function);
   this increases the risk of undetected error and makes debugging more
   complex. Is it really worth in practice? (Potential FIXME) */

#define cu_mpfr_round(a,b) cu_mpfr_rint((a), (b), CU_MPFR_RNDNA)
#define cu_mpfr_trunc(a,b) cu_mpfr_rint((a), (b), CU_MPFR_RNDZ)
#define cu_mpfr_ceil(a,b)  cu_mpfr_rint((a), (b), CU_MPFR_RNDU)
#define cu_mpfr_floor(a,b) cu_mpfr_rint((a), (b), CU_MPFR_RNDD)

#define cu_mpfr_cmp_ui(b,i) cu_mpfr_cmp_ui_2exp((b),(i),0)
#define cu_mpfr_cmp_si(b,i) cu_mpfr_cmp_si_2exp((b),(i),0)
#if __GNUC__ > 2 || __GNUC_MINOR__ >= 95
#define cu_mpfr_set(a,b,r)                         \
  __extension__ ({                              \
      cu_mpfr_srcptr _p = (b);                     \
      cu_mpfr_set4(a,_p,r,CU_MPFR_SIGN(_p));          \
    })
#endif
#define cu_mpfr_abs(a,b,r)  cu_mpfr_set4(a,b,r,1)
#define cu_mpfr_copysign(a,b,c,r) cu_mpfr_set4(a,b,r,CU_MPFR_GET_SIGN(c))
#define cu_mpfr_setsign(a,b,s,r) cu_mpfr_set4(a,b,r,(s) ? -1 : 1)
#define cu_mpfr_signbit(x)  (CU_MPFR_GET_SIGN(x) < 0)
#define cu_mpfr_cmp(b, c)   cu_mpfr_cmp3(b, c, 1)
#define cu_mpfr_mul_2exp(y,x,n,r) cu_mpfr_mul_2ui((y),(x),(n),(r))
#define cu_mpfr_div_2exp(y,x,n,r) cu_mpfr_div_2ui((y),(x),(n),(r))


/* When using GCC or ICC, optimize certain common comparisons and affectations.
   Added casts to improve robustness in case of undefined behavior and
   compiler extensions based on UB (in particular -fwrapv). MPFR doesn't
   use such extensions, but these macros will be used by 3rd-party code,
   where such extensions may be required.
   Moreover casts to unsigned long have been added to avoid warnings in
   programs that use MPFR and are compiled with -Wconversion; such casts
   are OK since if X is a constant expression, then (unsigned long) X is
   also a constant expression, so that the optimizations still work. The
   warnings are probably related to the following two bugs:
     https://gcc.gnu.org/bugzilla/show_bug.cgi?id=4210
     https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38470 (possibly a variant)
   and the casts could be removed once these bugs are fixed.
   Casts shouldn't be used on the generic calls (to the ..._2exp functions),
   where implicit conversions are performed. Indeed, having at least one
   implicit conversion in the macro allows the compiler to emit diagnostics
   when normally expected, for instance in the following call:
     cu_mpfr_set_ui (x, "foo", CU_MPFR_RNDN);
   If this is not possible (for future macros), one of the tricks described on
   https://groups.google.com/g/comp.std.c/c/9Jl0giNILfg/m/e6-evyS9KukJ?pli=1
   could be used. */
#if defined (__GNUC__) && !defined(__cplusplus)
#if (__GNUC__ >= 2)

#undef cu_mpfr_cmp_ui
/* We use the fact that cu_mpfr_sgn on NaN sets the erange flag and returns 0.
   But warning! cu_mpfr_sgn is specified as a macro in the API, thus the macro
   mustn't be used if side effects are possible, like here. */
#define cu_mpfr_cmp_ui(_f,_u)                                      \
  (__builtin_constant_p (_u) && (cu_mpfr_ulong) (_u) == 0 ?        \
   (cu_mpfr_sgn) (_f) :                                            \
   cu_mpfr_cmp_ui_2exp ((_f), (_u), 0))

#undef cu_mpfr_cmp_si
#define cu_mpfr_cmp_si(_f,_s)                                      \
  (__builtin_constant_p (_s) && (cu_mpfr_long) (_s) >= 0 ?         \
   cu_mpfr_cmp_ui ((_f), (cu_mpfr_ulong) (cu_mpfr_long) (_s)) :          \
   cu_mpfr_cmp_si_2exp ((_f), (_s), 0))

#if __GNUC__ > 2 || __GNUC_MINOR__ >= 95
#undef cu_mpfr_set_ui
#define cu_mpfr_set_ui(_f,_u,_r)                                   \
  (__builtin_constant_p (_u) && (cu_mpfr_ulong) (_u) == 0 ?        \
   __extension__ ({                                             \
       cu_mpfr_ptr _p = (_f);                                      \
       _p->_mpfr_sign = 1;                                      \
       _p->_mpfr_exp = __CU_MPFR_EXP_ZERO;                         \
       (cu_mpfr_void) (_r); 0; }) :                                \
   cu_mpfr_set_ui_2exp ((_f), (_u), 0, (_r)))
#endif

#undef cu_mpfr_set_si
#define cu_mpfr_set_si(_f,_s,_r)                                   \
  (__builtin_constant_p (_s) && (cu_mpfr_long) (_s) >= 0 ?         \
   cu_mpfr_set_ui ((_f), (cu_mpfr_ulong) (cu_mpfr_long) (_s), (_r)) :    \
   cu_mpfr_set_si_2exp ((_f), (_s), 0, (_r)))

#if __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
/* If the source is a constant number that is a power of 2,
   optimize the call */
#undef cu_mpfr_mul_ui
#define cu_mpfr_mul_ui(_f, _g, _u,_r)                              \
  (__builtin_constant_p (_u) && (cu_mpfr_ulong) (_u) >= 1 &&       \
   ((cu_mpfr_ulong) (_u) & ((cu_mpfr_ulong) (_u) - 1)) == 0 ?         \
   cu_mpfr_mul_2si((_f), (_g), __builtin_ctzl (_u), (_r)) :        \
   cu_mpfr_mul_ui ((_f), (_g), (_u), (_r)))
#undef cu_mpfr_div_ui
#define cu_mpfr_div_ui(_f, _g, _u,_r)                              \
  (__builtin_constant_p (_u) && (cu_mpfr_ulong) (_u) >= 1 &&       \
   ((cu_mpfr_ulong) (_u) & ((cu_mpfr_ulong) (_u) - 1)) == 0 ?         \
   cu_mpfr_mul_2si((_f), (_g), - __builtin_ctzl (_u), (_r)) :      \
   cu_mpfr_div_ui ((_f), (_g), (_u), (_r)))
#endif

/* If the source is a constant number that is non-negative,
   optimize the call */
#undef cu_mpfr_mul_si
#define cu_mpfr_mul_si(_f, _g, _s,_r)                                      \
  (__builtin_constant_p (_s) && (cu_mpfr_long) (_s) >= 0 ?                 \
   cu_mpfr_mul_ui ((_f), (_g), (cu_mpfr_ulong) (cu_mpfr_long) (_s), (_r)) :      \
   cu_mpfr_mul_si ((_f), (_g), (_s), (_r)))
#undef cu_mpfr_div_si
#define cu_mpfr_div_si(_f, _g, _s,_r)                                      \
  (__builtin_constant_p (_s) && (cu_mpfr_long) (_s) >= 0 ?                 \
   cu_mpfr_div_ui ((_f), (_g), (cu_mpfr_ulong) (cu_mpfr_long) (_s), (_r)) :      \
   cu_mpfr_div_si ((_f), (_g), (_s), (_r)))

#endif
#endif

/* Macro versions of the custom interface for fast access. */

/* The internal cast to cu_mpfr_size_t will silent a warning with
   GCC's -Wsign-conversion that could occur with user code, as
   sizeof is of type size_t, which is unsigned. */
#define cu_mpfr_custom_get_size(p)                                             \
  ((cu_mpfr_size_t)                                                            \
   ((cu_mpfr_size_t) (((cu_mpfr_prec_t)(p) + CU_GMP_NUMB_BITS - 1) / CU_GMP_NUMB_BITS)  \
    * sizeof (cu_mp_limb_t)))

#define cu_mpfr_custom_init(m,p) ((void) (m), (void) (p))

#define cu_mpfr_custom_get_significand(x) \
  ((cu_mpfr_void *) CU_MPFR_VALUE_OF(CU_MPFR_SRCPTR(x)->_mpfr_d))

#define cu_mpfr_custom_get_exp(x) CU_MPFR_VALUE_OF(CU_MPFR_SRCPTR(x)->_mpfr_exp)

#define cu_mpfr_custom_move(x,m) (((cu_mpfr_ptr) (x))->_mpfr_d = (cu_mp_limb_t *) (m))

/* Note: the following macro is not usable in contexts where an expression
   is expected. */
#define cu_mpfr_custom_init_set(x,k,e,p,m) do {                   \
  cu_mpfr_ptr _x = (x);                                           \
  cu_mpfr_exp_t _e = (e);                                         \
  cu_mpfr_kind_t _t;                                              \
  cu_mpfr_int _s, _k;                                             \
  _k = (k);                                                    \
  if (_k >= 0)  {                                              \
    _t = (cu_mpfr_kind_t) _k;                                     \
    _s = 1;                                                    \
  } else {                                                     \
    _t = (cu_mpfr_kind_t) - _k;                                   \
    _s = -1;                                                   \
  }                                                            \
  _e = _t == CU_MPFR_REGULAR_KIND ? _e :                          \
    _t == CU_MPFR_NAN_KIND ? __CU_MPFR_EXP_NAN :                     \
    _t == CU_MPFR_INF_KIND ? __CU_MPFR_EXP_INF : __CU_MPFR_EXP_ZERO;    \
  _x->_mpfr_prec = (p);                                        \
  _x->_mpfr_sign = _s;                                         \
  _x->_mpfr_exp  = _e;                                         \
  _x->_mpfr_d    = (cu_mp_limb_t*) (m);                           \
 } while (0)

#if __GNUC__ > 2 || __GNUC_MINOR__ >= 95
#define cu_mpfr_custom_get_kind(x)                                         \
  __extension__ ({                                                      \
    cu_mpfr_srcptr _x = (x);                                               \
    _x->_mpfr_exp >  __CU_MPFR_EXP_INF ?                                   \
      (cu_mpfr_int) CU_MPFR_REGULAR_KIND * CU_MPFR_SIGN (_x)                     \
      : _x->_mpfr_exp == __CU_MPFR_EXP_INF ?                               \
      (cu_mpfr_int) CU_MPFR_INF_KIND * CU_MPFR_SIGN (_x)                         \
      : _x->_mpfr_exp == __CU_MPFR_EXP_NAN ? (cu_mpfr_int) CU_MPFR_NAN_KIND      \
      : (cu_mpfr_int) CU_MPFR_ZERO_KIND * CU_MPFR_SIGN (_x);                     \
  })
#else
#define cu_mpfr_custom_get_kind(x) ((cu_mpfr_custom_get_kind)(x))
#endif

/* End of the macro versions of the custom interface. */

#endif /* CU_MPFR_USE_NO_MACRO */

/* These are defined to be macros */
#define cu_mpfr_init_set_si(x, i, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_si((x), (i), (rnd)) )
#define cu_mpfr_init_set_ui(x, i, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_ui((x), (i), (rnd)) )
#define cu_mpfr_init_set_d(x, d, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_d((x), (d), (rnd)) )
#define cu_mpfr_init_set_ld(x, d, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_ld((x), (d), (rnd)) )
#define cu_mpfr_init_set_z(x, i, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_z((x), (i), (rnd)) )
#ifndef CU_MPFR_USE_MINI_GMP
#define cu_mpfr_init_set_q(x, i, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_q((x), (i), (rnd)) )
#define cu_mpfr_init_set_f(x, y, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set_f((x), (y), (rnd)) )
#endif
#define cu_mpfr_init_set(x, y, rnd) \
 ( cu_mpfr_init(x), cu_mpfr_set((x), (y), (rnd)) )

/* Compatibility layer -- obsolete functions and macros */
/* Note: it is not possible to output warnings, unless one defines
 * a deprecated variable and uses it, e.g.
 *   CU_MPFR_DEPRECATED extern int cu_mpfr_deprecated_feature;
 *   #define CU_MPFR_EMIN_MIN ((void)cu_mpfr_deprecated_feature,cu_mpfr_get_emin_min())
 * (the cast to void avoids a warning because the left-hand operand
 * has no effect).
 */
#define cu_mpfr_cmp_abs cu_mpfr_cmpabs
#define cu_mpfr_round_prec(x,r,p) cu_mpfr_prec_round(x,p,r)
#define cu___gmp_default_rounding_mode (cu_mpfr_get_default_rounding_mode())
#define cu___mpfr_emin (cu_mpfr_get_emin())
#define cu___mpfr_emax (cu_mpfr_get_emax())
#define cu___mpfr_default_fp_bit_precision (cu_mpfr_get_default_fp_bit_precision())
#define CU_MPFR_EMIN_MIN cu_mpfr_get_emin_min()
#define CU_MPFR_EMIN_MAX cu_mpfr_get_emin_max()
#define CU_MPFR_EMAX_MIN cu_mpfr_get_emax_min()
#define CU_MPFR_EMAX_MAX cu_mpfr_get_emax_max()
#define cu_mpfr_version (cu_mpfr_get_version())
#ifndef cu_mpz_set_fr
# define cu_mpz_set_fr cu_mpfr_get_z
#endif
#define cu_mpfr_get_z_exp cu_mpfr_get_z_2exp
#define cu_mpfr_custom_get_mantissa cu_mpfr_custom_get_significand

#endif /* CU_MPC_CUDA_MPFR_H */


/* Check if <stdint.h> / <inttypes.h> is included or if the user
   explicitly wants intmax_t. Automatic detection is done by
   checking:
     - INTMAX_C and UINTMAX_C, but not if the compiler is a C++ one
       (as suggested by Patrick Pelissier) because the test does not
       work well in this case. See:
         https://sympa.inria.fr/sympa/arc/mpfr/2010-02/msg00025.html
       We do not check INTMAX_MAX and UINTMAX_MAX because under Solaris,
       these macros are always defined by <limits.h> (i.e. even when
       <stdint.h> and <inttypes.h> are not included).
     - _STDINT_H (defined by the glibc), _STDINT_H_ (defined under
       Mac OS X) and _STDINT (defined under MS Visual Studio), but
       this test may not work with all implementations.
       Portable software should not rely on these tests.
*/
#if (defined (INTMAX_C) && defined (UINTMAX_C) && !defined(__cplusplus)) || \
  defined (CU_MPFR_USE_INTMAX_T) || \
  defined (_STDINT_H) || defined (_STDINT_H_) || defined (_STDINT) || \
  defined (_SYS_STDINT_H_) /* needed for FreeBSD */
# ifndef _MPFR_H_HAVE_INTMAX_T
# define _MPFR_H_HAVE_INTMAX_T 1

#if defined (__cplusplus)
extern "C" {
#endif

#define cu_mpfr_set_sj cu___gmpfr_set_sj
#define cu_mpfr_set_sj_2exp cu___gmpfr_set_sj_2exp
#define cu_mpfr_set_uj cu___gmpfr_set_uj
#define cu_mpfr_set_uj_2exp cu___gmpfr_set_uj_2exp
#define cu_mpfr_get_sj cu___gmpfr_mpfr_get_sj
#define cu_mpfr_get_uj cu___gmpfr_mpfr_get_uj
#define cu_mpfr_pow_uj cu___gmpfr_mpfr_pow_uj
#define cu_mpfr_pow_sj cu___gmpfr_mpfr_pow_sj
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_sj (cu_mpfr_ptr, intmax_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_sj_2exp (cu_mpfr_ptr, intmax_t, intmax_t,
                                      cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_uj (cu_mpfr_ptr, uintmax_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_set_uj_2exp (cu_mpfr_ptr, uintmax_t, intmax_t,
                                      cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC intmax_t cu_mpfr_get_sj (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC uintmax_t cu_mpfr_get_uj (cu_mpfr_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow_uj (cu_mpfr_ptr, cu_mpfr_srcptr, uintmax_t, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_pow_sj (cu_mpfr_ptr, cu_mpfr_srcptr, intmax_t, cu_mpfr_rnd_t);
/* define cu_mpfr_pown (defined in IEEE 754-2019) as an alias for cu_mpfr_pow_sj.
   It is currently implemented as a macro, but this may change in the future
   (it could be implemented as an inline function); in case of change, update
   the manual. */
#define cu_mpfr_pown cu_mpfr_pow_sj

#if defined (__cplusplus)
}
#endif

# endif /* _MPFR_H_HAVE_INTMAX_T */
#endif


/* Check if <stdio.h> has been included or if the user wants FILE */
#if defined (_GMP_H_HAVE_FILE) || defined (CU_MPFR_USE_FILE)
# ifndef _MPFR_H_HAVE_FILE
# define _MPFR_H_HAVE_FILE 1

#if defined (__cplusplus)
extern "C" {
#endif

#define cu_mpfr_inp_str cu___gmpfr_inp_str
#define cu_mpfr_out_str cu___gmpfr_out_str
__host__ __device__ __CU_MPFR_DECLSPEC size_t cu_mpfr_inp_str (cu_mpfr_ptr, FILE*, int, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPFR_DECLSPEC size_t cu_mpfr_out_str (FILE*, int, size_t, cu_mpfr_srcptr,
                                     cu_mpfr_rnd_t);
#ifndef CU_MPFR_USE_MINI_GMP
#define cu_mpfr_fprintf cu___gmpfr_fprintf
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fprintf (FILE*, const char*, ...);
#endif
#define cu_mpfr_fpif_export cu___gmpfr_fpif_export
#define cu_mpfr_fpif_import cu___gmpfr_fpif_import
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fpif_export (FILE*, cu_mpfr_ptr);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_fpif_import (cu_mpfr_ptr, FILE*);

#if defined (__cplusplus)
}
#endif

# endif /* _MPFR_H_HAVE_FILE */
#endif


/* check if <stdarg.h> has been included or if the user wants va_list */
#if defined (_GMP_H_HAVE_VA_LIST) || defined (CU_MPFR_USE_VA_LIST)
# ifndef _MPFR_H_HAVE_VA_LIST
# define _MPFR_H_HAVE_VA_LIST 1

#if defined (__cplusplus)
extern "C" {
#endif

#define cu_mpfr_vprintf cu___gmpfr_vprintf
#define cu_mpfr_vasprintf cu___gmpfr_vasprintf
#define cu_mpfr_vsprintf cu___gmpfr_vsprintf
#define cu_mpfr_vsnprintf cu___gmpfr_vsnprintf
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_vprintf (const char*, va_list);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_vasprintf (char**, const char*, va_list);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_vsprintf (char*, const char*, va_list);
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_vsnprintf (char*, size_t, const char*, va_list);

#if defined (__cplusplus)
}
#endif

# endif /* _MPFR_H_HAVE_VA_LIST */
#endif


/* check if <stdarg.h> has been included and if FILE is available
   (see above) */
#if defined (_MPFR_H_HAVE_VA_LIST) && defined (_MPFR_H_HAVE_FILE)
# ifndef _MPFR_H_HAVE_VA_LIST_FILE
# define _MPFR_H_HAVE_VA_LIST_FILE 1

#if defined (__cplusplus)
extern "C" {
#endif

#define cu_mpfr_vfprintf cu___gmpfr_vfprintf
__host__ __device__ __CU_MPFR_DECLSPEC int cu_mpfr_vfprintf (FILE*, const char*, va_list);

#if defined (__cplusplus)
}
#endif

# endif /* _MPFR_H_HAVE_VA_LIST_FILE */
#endif
