/* Auto-generated by tools/make_umbrella.py -- do NOT edit by hand.
 * Fully cu_/CU_-namespaced public header: every type, enum constant,
 * macro and include guard is prefixed so this coexists with the system
 * <gmp.h>/<mpfr.h>/<mpc.h> in the SAME translation unit. */
/* CUDA-adapted from MPC by tools/cudafy_mpc.py. */
/* mpc.h -- Include file for mpc.

Copyright (C) 2002, 2003, 2004, 2005, 2007, 2008, 2009, 2010, 2011, 2012, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024, 2026 INRIA

This file is part of GNU MPC.

GNU MPC is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

GNU MPC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see http://www.gnu.org/licenses/ .
*/

#ifndef CU_MPC_CUDA_MPC_H
#define CU_MPC_CUDA_MPC_H

#include <stdint.h>
#include "mpc_cuda/cu_gmp.h"
#include "mpc_cuda/cu_mpfr.h"

#if 0
#define _MPC_HAVE_COMPLEX_H
#else
#undef _MPC_HAVE_COMPLEX_H
#endif

/* Define MPC version number */
#define CU_MPC_VERSION_MAJOR 1
#define CU_MPC_VERSION_MINOR 4
#define CU_MPC_VERSION_PATCHLEVEL 1
#define CU_MPC_VERSION_STRING "1.4.1"

/* Macros dealing with MPC VERSION */
#define CU_MPC_VERSION_NUM(a,b,c) (((a) << 16L) | ((b) << 8) | (c))
#define CU_MPC_VERSION                                                     \
  CU_MPC_VERSION_NUM(CU_MPC_VERSION_MAJOR,CU_MPC_VERSION_MINOR,CU_MPC_VERSION_PATCHLEVEL)

/* Check if stdint.h/inttypes.h is included */
#if defined (INTMAX_C) && defined (UINTMAX_C)
#define _MPC_H_HAVE_INTMAX_T 1
#endif

/* Return values */

/* Transform negative to 2, positive to 1, leave 0 unchanged.
   Warning: since inex is evaluated two times, we should avoid
   CU_MPC_INEX(cu_mpc_mul (...), cu_mpc_mul (...)) */
#define CU_MPC_INEX_POS(inex) (((inex) < 0) ? 2 : ((inex) == 0) ? 0 : 1)
/* Transform 2 to negative, 1 to positive, leave 0 unchanged */
#define CU_MPC_INEX_NEG(inex) (((inex) == 2) ? -1 : ((inex) == 0) ? 0 : 1)

/* The global inexact flag is made of (real flag) + 4 * (imaginary flag), where
   each of the real and imaginary inexact flag are:
   0 when the result is exact (no rounding error)
   1 when the result is larger than the exact value
   2 when the result is smaller than the exact value */
#define CU_MPC_INEX(inex_re, inex_im) \
        (CU_MPC_INEX_POS(inex_re) | (CU_MPC_INEX_POS(inex_im) << 2))
#define CU_MPC_INEX_RE(inex) CU_MPC_INEX_NEG((inex) & 3)
#define CU_MPC_INEX_IM(inex) CU_MPC_INEX_NEG((inex) >> 2)

/* For functions computing two results, the return value is
   inexact1+16*inexact2, which is 0 iif both results are exact. */
#define CU_MPC_INEX12(inex1, inex2) (inex1 | (inex2 << 4))
#define CU_MPC_INEX1(inex) (inex & 15)
#define CU_MPC_INEX2(inex) (inex >> 4)

/* Definition of rounding modes */

/* a complex rounding mode is just a pair of two real rounding modes
   we reserve four bits for a real rounding mode.  */
typedef int cu_mpc_rnd_t;

#define CU_MPC_RND(r1,r2) (((int)(r1)) + ((int)(r2) << 4))
#define CU_MPC_RND_RE(x) ((cu_mpfr_rnd_t)((x) & 0x0F))
#define CU_MPC_RND_IM(x) ((cu_mpfr_rnd_t)((x) >> 4))

#define CU_MPC_RNDNN CU_MPC_RND (CU_MPFR_RNDN,CU_MPFR_RNDN)
#define CU_MPC_RNDNZ CU_MPC_RND (CU_MPFR_RNDN,CU_MPFR_RNDZ)
#define CU_MPC_RNDNU CU_MPC_RND (CU_MPFR_RNDN,CU_MPFR_RNDU)
#define CU_MPC_RNDND CU_MPC_RND (CU_MPFR_RNDN,CU_MPFR_RNDD)
#define CU_MPC_RNDNA CU_MPC_RND (CU_MPFR_RNDN,CU_MPFR_RNDA)

#define CU_MPC_RNDZN CU_MPC_RND (CU_MPFR_RNDZ,CU_MPFR_RNDN)
#define CU_MPC_RNDZZ CU_MPC_RND (CU_MPFR_RNDZ,CU_MPFR_RNDZ)
#define CU_MPC_RNDZU CU_MPC_RND (CU_MPFR_RNDZ,CU_MPFR_RNDU)
#define CU_MPC_RNDZD CU_MPC_RND (CU_MPFR_RNDZ,CU_MPFR_RNDD)
#define CU_MPC_RNDZA CU_MPC_RND (CU_MPFR_RNDZ,CU_MPFR_RNDA)

#define CU_MPC_RNDUN CU_MPC_RND (CU_MPFR_RNDU,CU_MPFR_RNDN)
#define CU_MPC_RNDUZ CU_MPC_RND (CU_MPFR_RNDU,CU_MPFR_RNDZ)
#define CU_MPC_RNDUU CU_MPC_RND (CU_MPFR_RNDU,CU_MPFR_RNDU)
#define CU_MPC_RNDUD CU_MPC_RND (CU_MPFR_RNDU,CU_MPFR_RNDD)
#define CU_MPC_RNDUA CU_MPC_RND (CU_MPFR_RNDU,CU_MPFR_RNDA)

#define CU_MPC_RNDDN CU_MPC_RND (CU_MPFR_RNDD,CU_MPFR_RNDN)
#define CU_MPC_RNDDZ CU_MPC_RND (CU_MPFR_RNDD,CU_MPFR_RNDZ)
#define CU_MPC_RNDDU CU_MPC_RND (CU_MPFR_RNDD,CU_MPFR_RNDU)
#define CU_MPC_RNDDD CU_MPC_RND (CU_MPFR_RNDD,CU_MPFR_RNDD)
#define CU_MPC_RNDDA CU_MPC_RND (CU_MPFR_RNDD,CU_MPFR_RNDA)

#define CU_MPC_RNDAN CU_MPC_RND (CU_MPFR_RNDA,CU_MPFR_RNDN)
#define CU_MPC_RNDAZ CU_MPC_RND (CU_MPFR_RNDA,CU_MPFR_RNDZ)
#define CU_MPC_RNDAU CU_MPC_RND (CU_MPFR_RNDA,CU_MPFR_RNDU)
#define CU_MPC_RNDAD CU_MPC_RND (CU_MPFR_RNDA,CU_MPFR_RNDD)
#define CU_MPC_RNDAA CU_MPC_RND (CU_MPFR_RNDA,CU_MPFR_RNDA)


/* Definitions of types and their semantics */

typedef struct {
  cu_mpfr_t re;
  cu_mpfr_t im;
}
cu___mpc_struct;

typedef cu___mpc_struct cu_mpc_t[1];
typedef cu___mpc_struct *cu_mpc_ptr;
typedef const cu___mpc_struct *cu_mpc_srcptr;

typedef struct {
   int64_t mant;
   int64_t exp;
}
cu___mpcr_struct;

typedef cu___mpcr_struct cu_mpcr_t [1];
typedef cu___mpcr_struct *cu_mpcr_ptr;
typedef const cu___mpcr_struct *cu_mpcr_srcptr;

typedef struct {
  cu_mpc_t  c;
  cu_mpcr_t r;
}
cu___mpcb_struct;

typedef cu___mpcb_struct cu_mpcb_t [1];
typedef cu___mpcb_struct *cu_mpcb_ptr;
typedef const cu___mpcb_struct *cu_mpcb_srcptr;

/* Support for WINDOWS DLL, see
   https://sympa.inria.fr/sympa/arc/mpc-discuss/2011-11/ ;
   when building the DLL, export symbols, otherwise behave as GMP           */
#if defined (__CU_MPC_LIBRARY_BUILD) && __CU_GMP_LIBGMP_DLL
#define __CU_MPC_DECLSPEC __CU_GMP_DECLSPEC_EXPORT
#else
#define __CU_MPC_DECLSPEC __CU_GMP_DECLSPEC
#endif

#if defined (__cplusplus)
extern "C" {
#endif

__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_add       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_add_fr    (cu_mpc_ptr, cu_mpc_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_add_si    (cu_mpc_ptr, cu_mpc_srcptr, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_add_ui    (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sub       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sub_fr    (cu_mpc_ptr, cu_mpc_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_fr_sub    (cu_mpc_ptr, cu_mpfr_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sub_ui    (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_ui_ui_sub (cu_mpc_ptr, unsigned long int, unsigned long int, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_fr    (cu_mpc_ptr, cu_mpc_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_ui    (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_si    (cu_mpc_ptr, cu_mpc_srcptr, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_i     (cu_mpc_ptr, cu_mpc_srcptr, int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sqr       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_div       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_fr    (cu_mpc_ptr, cu_mpc_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_ld    (cu_mpc_ptr, cu_mpc_srcptr, long double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_d     (cu_mpc_ptr, cu_mpc_srcptr, double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_si    (cu_mpc_ptr, cu_mpc_srcptr, long, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_ui    (cu_mpc_ptr, cu_mpc_srcptr, unsigned long, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_pow_z     (cu_mpc_ptr, cu_mpc_srcptr, cu_mpz_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_div_fr    (cu_mpc_ptr, cu_mpc_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_fr_div    (cu_mpc_ptr, cu_mpfr_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_div_ui    (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_ui_div    (cu_mpc_ptr, unsigned long int, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_div_2ui   (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_2ui   (cu_mpc_ptr, cu_mpc_srcptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_div_2si   (cu_mpc_ptr, cu_mpc_srcptr, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_mul_2si   (cu_mpc_ptr, cu_mpc_srcptr, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_conj      (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_neg       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sum (cu_mpc_ptr, const cu_mpc_ptr *, unsigned long, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_dot (cu_mpc_ptr, const cu_mpc_ptr *, const cu_mpc_ptr *, unsigned long, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_norm      (cu_mpfr_ptr, cu_mpc_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_abs       (cu_mpfr_ptr, cu_mpc_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sqrt      (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_d     (cu_mpc_ptr, double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_d_d   (cu_mpc_ptr, double, double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_ld    (cu_mpc_ptr, long double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_ld_ld (cu_mpc_ptr, long double, long double, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_f     (cu_mpc_ptr, cu_mpf_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_f_f   (cu_mpc_ptr, cu_mpf_srcptr, cu_mpf_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_fr    (cu_mpc_ptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_fr_fr (cu_mpc_ptr, cu_mpfr_srcptr, cu_mpfr_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_q     (cu_mpc_ptr, cu_mpq_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_q_q   (cu_mpc_ptr, cu_mpq_srcptr, cu_mpq_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_si    (cu_mpc_ptr, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_si_si (cu_mpc_ptr, long int, long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_ui    (cu_mpc_ptr, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_ui_ui (cu_mpc_ptr, unsigned long int, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_z     (cu_mpc_ptr, cu_mpz_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_z_z   (cu_mpc_ptr, cu_mpz_srcptr, cu_mpz_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_swap      (cu_mpc_ptr, cu_mpc_ptr);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_fma       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);

__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_set_nan   (cu_mpc_ptr);

__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_real        (cu_mpfr_ptr, cu_mpc_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_imag        (cu_mpfr_ptr, cu_mpc_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_arg         (cu_mpfr_ptr, cu_mpc_srcptr, cu_mpfr_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_proj        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_cmp         (cu_mpc_srcptr, cu_mpc_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_cmp_si_si   (cu_mpc_srcptr, long int, long int);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_cmp_abs     (cu_mpc_srcptr, cu_mpc_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_exp         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_exp10       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_exp2        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_log         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_log10       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_log2        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_agm         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sin         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_cos         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sin_cos     (cu_mpc_ptr, cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_tan         (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_sinh        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_cosh        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_tanh        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_asin        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_acos        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_atan        (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_asinh       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_acosh       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_atanh       (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_rootofunity (cu_mpc_ptr, unsigned long int, unsigned long int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_clear       (cu_mpc_ptr);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_urandom     (cu_mpc_ptr, cu_gmp_randstate_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_init2       (cu_mpc_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_init3       (cu_mpc_ptr, cu_mpfr_prec_t, cu_mpfr_prec_t);
__host__ __device__ __CU_MPC_DECLSPEC cu_mpfr_prec_t cu_mpc_get_prec (cu_mpc_srcptr x);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_get_prec2   (cu_mpfr_prec_t *pr, cu_mpfr_prec_t *pi, cu_mpc_srcptr x);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_set_prec    (cu_mpc_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPC_DECLSPEC const char * cu_mpc_get_version (void);

__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_strtoc      (cu_mpc_ptr, const char *, char **, int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_str     (cu_mpc_ptr, const char *, int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC char * cu_mpc_get_str   (int, size_t, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpc_free_str    (char *);

/* declare certain functions only if appropriate headers have been included */
#ifdef _MPC_H_HAVE_INTMAX_T
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_sj      (cu_mpc_ptr, intmax_t, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_uj      (cu_mpc_ptr, uintmax_t,  cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_sj_sj   (cu_mpc_ptr, intmax_t, intmax_t, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_uj_uj   (cu_mpc_ptr, uintmax_t, uintmax_t, cu_mpc_rnd_t);
#endif

/* Microsoft Compiler does not have complex/_Complex, see
   https://learn.microsoft.com/en-US/cpp/c-runtime-library/complex-math-support?view=msvc-170
   If you change this, also check tests/read_description.c.
*/
#ifdef _MSC_VER
#define DOUBLE_COMPLEX _Dcomplex
#define LONG_DOUBLE_COMPLEX _Lcomplex
#else
#define DOUBLE_COMPLEX double _Complex
#define LONG_DOUBLE_COMPLEX long double _Complex
#endif

#if defined (_MPC_HAVE_COMPLEX_H) && defined (_Complex_I)
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_dc      (cu_mpc_ptr, DOUBLE_COMPLEX, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int  cu_mpc_set_ldc     (cu_mpc_ptr, LONG_DOUBLE_COMPLEX, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC DOUBLE_COMPLEX cu_mpc_get_dc (cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC LONG_DOUBLE_COMPLEX cu_mpc_get_ldc (cu_mpc_srcptr, cu_mpc_rnd_t);
#endif

#ifdef _GMP_H_HAVE_FILE
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpc_inp_str    (cu_mpc_ptr, FILE *, size_t *, int, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC size_t cu_mpc_out_str (FILE *, int, size_t, cu_mpc_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_out_str  (FILE *f, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_out_str (FILE *f, cu_mpcr_srcptr r);
#endif

__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcr_inf_p (cu_mpcr_srcptr r);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcr_zero_p (cu_mpcr_srcptr r);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcr_lt_half_p (cu_mpcr_srcptr r);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcr_cmp (cu_mpcr_srcptr r, cu_mpcr_srcptr s);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_set_inf (cu_mpcr_ptr r);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_set_zero (cu_mpcr_ptr r);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_set_one (cu_mpcr_ptr r);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_set (cu_mpcr_ptr r, cu_mpcr_srcptr s);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_set_ui64_2si64 (cu_mpcr_ptr r, uint64_t mant,
   int64_t exp);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_max (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t);
__host__ __device__ __CU_MPC_DECLSPEC int64_t cu_mpcr_get_exp (cu_mpcr_srcptr r);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_mul (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_mul_2ui (cu_mpcr_ptr r, cu_mpcr_srcptr s,
   unsigned long int e);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_sqr (cu_mpcr_ptr r, cu_mpcr_srcptr s);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_add (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_sub (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_sub_rnd (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t,
   cu_mpfr_rnd_t rnd);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_div (cu_mpcr_ptr r, cu_mpcr_srcptr s, cu_mpcr_srcptr t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_div_2ui (cu_mpcr_ptr r, cu_mpcr_srcptr s,
   unsigned long int e);
__host__ __device__ __CU_MPC_DECLSPEC int64_t sqrt_int64 (int64_t n);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_sqrt (cu_mpcr_ptr r, cu_mpcr_srcptr s);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_add_rounding_error (cu_mpcr_ptr r, cu_mpfr_prec_t p,
   cu_mpfr_rnd_t rnd);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcr_c_abs_rnd (cu_mpcr_ptr r, cu_mpc_srcptr z,
   cu_mpfr_rnd_t rnd);

__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_init (cu_mpcb_ptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_clear (cu_mpcb_ptr);
__host__ __device__ __CU_MPC_DECLSPEC cu_mpfr_prec_t cu_mpcb_get_prec (cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_set_prec (cu_mpcb_ptr, cu_mpfr_prec_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_set (cu_mpcb_ptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_set_inf (cu_mpcb_ptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_set_c (cu_mpcb_ptr, cu_mpc_srcptr, cu_mpfr_prec_t,
   unsigned long int, unsigned long int);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_set_ui_ui (cu_mpcb_ptr, unsigned long int,
   unsigned long int, cu_mpfr_prec_t);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_neg (cu_mpcb_ptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_mul (cu_mpcb_ptr, cu_mpcb_srcptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_sqr (cu_mpcb_ptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_pow_ui (cu_mpcb_ptr, cu_mpcb_srcptr, unsigned long int);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_add (cu_mpcb_ptr, cu_mpcb_srcptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_sqrt (cu_mpcb_ptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_div (cu_mpcb_ptr, cu_mpcb_srcptr, cu_mpcb_srcptr);
__host__ __device__ __CU_MPC_DECLSPEC void cu_mpcb_div_2ui (cu_mpcb_ptr, cu_mpcb_srcptr, unsigned long int);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcb_can_round (cu_mpcb_srcptr, cu_mpfr_prec_t, cu_mpfr_prec_t,
   cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpcb_round (cu_mpc_ptr, cu_mpcb_srcptr, cu_mpc_rnd_t);
__host__ __device__ __CU_MPC_DECLSPEC int cu_mpc_eta_fund (cu_mpc_ptr, cu_mpc_srcptr, cu_mpc_rnd_t);

#if defined (__cplusplus)
}
#endif

#define cu_mpc_realref(x) ((x)->re)
#define cu_mpc_imagref(x) ((x)->im)

#define cu_mpc_cmp_si(x, y) \
 ( cu_mpc_cmp_si_si ((x), (y), 0l) )
#define cu_mpc_ui_sub(x, y, z, r) cu_mpc_ui_ui_sub (x, y, 0ul, z, r)

/*
   Define a fake cu_mpfr_set_fr so that, for instance, cu_mpc_set_fr_z would
   be defined as follows:
   cu_mpc_set_fr_z (cu_mpc_t rop, cu_mpfr_t x, cu_mpz_t y, cu_mpc_rnd_t rnd)
       CU_MPC_SET_X_Y (fr, z, rop, x, y, rnd)
*/
#ifndef cu_mpfr_set_fr
#define cu_mpfr_set_fr cu_mpfr_set
#endif
#define CU_MPC_SET_X_Y(real_t, imag_t, z, real_value, imag_value, rnd)     \
  {                                                                     \
    int _inex_re, _inex_im;                                             \
    _inex_re = (cu_mpfr_set_ ## real_t) (cu_mpc_realref (z), (real_value), CU_MPC_RND_RE (rnd)); \
    _inex_im = (cu_mpfr_set_ ## imag_t) (cu_mpc_imagref (z), (imag_value), CU_MPC_RND_IM (rnd)); \
    return CU_MPC_INEX (_inex_re, _inex_im);                               \
  }

#endif /* ifndef CU_MPC_CUDA_MPC_H */
